const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const source = fs.readFileSync(path.join(__dirname, '../src/Asap.Web/Frontend/staff/js/draft-scope.js'), 'utf8');
  const { createDraftScope } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
  const scope = createDraftScope();
  const root = { isConnected: true };
  let value = 'baseline';
  const own = scope.register({ root, isDirty: () => value !== 'baseline' });
  const siblingRoot = { isConnected: true };
  let siblingDirty = false;
  const sibling = scope.register({ root: siblingRoot, isDirty: () => siblingDirty });
  assert.equal(scope.admit().allowed, false);
  assert.equal(scope.admit({}).reason, 'missing_consumption');
  assert.equal(scope.admit({ consumes: undefined }).allowed, false);
  value = 'draft';
  assert.equal(scope.isDirty(), true);
  assert.equal(scope.admit({ consumes: null }).allowed, false);
  assert.equal(scope.admit({ consumes: own }).allowed, true);
  assert.equal(scope.isDirty(), true, 'consumption grants permission without clearing at dispatch');
  siblingDirty = true;
  assert.equal(scope.admit({ consumes: own }).reason, 'competing_draft');
  value = 'baseline';
  assert.equal(scope.admit({ consumes: sibling }).allowed, true);
  const foreign = createDraftScope().register({ root, isDirty: () => true });
  assert.equal(scope.admit({ consumes: foreign }).reason, 'invalid_owner');
  siblingRoot.isConnected = false;
  assert.equal(scope.isDirty(), false);
  assert.equal(scope.admit({ consumes: sibling }).allowed, false);
  scope.release(own);
  assert.equal(scope.admit({ consumes: own }).allowed, false);
  scope.dispose();
  assert.equal(scope.admit({ consumes: null }).allowed, false);
  assert.throws(() => scope.register({ root, isDirty: () => false }));
  const replacement = createDraftScope();
  assert.equal(replacement.admit({ consumes: own }).allowed, false);
  assert.equal(replacement.admit({ consumes: null }).allowed, true);
  console.log('Local draft scope ownership, admission and disposal contracts passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
