import { runLegacyModule } from './runtime.js';

const source = [
  "undoRow = async function undoRow(id) {",
  "  if (!await showConfirm('Undo action', 'Undo action and return this suggestion to Suggestions?')) return;",
  "  const row = currentSuggestions.find(r => r.id === id);",
  "  if (!row) return;",
  "  try {",
  "    const res = await fetch(`/api/asap/staff/title-requests/${id}/action`, {",
  "      method: 'POST',",
  "      headers: {",
  "        'Content-Type': 'application/json',",
  "        'Authorization': pb.authStore.token",
  "      },",
  "      body: JSON.stringify({",
  "        ...row,",
  "        status: 'suggestion',",
  "        editedBy: pb.authStore.model.username",
  "      })",
  "    });",
  "    if (!res.ok) {",
  "      const data = await res.json().catch(() => ({}));",
  "      throw new Error(data.message || 'Error undoing suggestion');",
  "    }",
  "    loadTab(currentStatus);",
  "  } catch (err) {",
  "    await showAlert(err.message || 'Error undoing suggestion');",
  "  }",
  "}",
  "",
  "deleteClosedRequest = async function deleteClosedRequest(id) {",
  "  if (!isAdminStaff()) return;",
  "  const confirmed = await showConfirm('Delete this closed request?', 'This cannot be undone.');",
  "  if (!confirmed) return;",
  "  try {",
  "    await authorizedJson(`/api/asap/staff/requests/${encodeURIComponent(id)}`, { method: 'DELETE' });",
  "    showToast('Closed request deleted.', 'success');",
  "    loadTab(currentStatus);",
  "  } catch (err) {",
  "    await showAlert(err.message || 'Could not delete closed request.');",
  "  }",
  "}",
  "",
  "closeDuplicateRequest = async function closeDuplicateRequest(id) {",
  "  const row = currentSuggestions.find(r => r.id === id) || allSuggestions.find(r => r.id === id);",
  "  if (!row) return;",
  "  const confirmed = await showConfirm('Close this duplicate request?', 'The patron already has an open request or hold for this BIB ID.');",
  "  if (!confirmed) return;",
  "  try {",
  "    await authorizedJson(`/api/asap/staff/title-requests/${encodeURIComponent(id)}/action`, {",
  "      method: 'POST',",
  "      body: JSON.stringify({",
  "        action: 'closeDuplicate',",
  "        status: 'closed',",
  "        title: row.title || '',",
  "        author: row.author || '',",
  "        identifier: row.identifier || '',",
  "        bibid: row.bibid || '',",
  "        format: row.format || '',",
  "        agegroup: row.agegroup || '',",
  "        publication: row.publication || '',",
  "        exactPublicationDate: row.exactPublicationDate || '',",
  "        notes: row.notes || '',",
  "        editedBy: pb.authStore.model.username",
  "      })",
  "    });",
  "    showToast('Duplicate request closed.', 'success');",
  "    loadTab(currentStatus);",
  "  } catch (err) {",
  "    await showAlert(err.message || 'Could not close duplicate request.');",
  "  }",
  "}",
  "",
  "document.getElementById('close-modal-x').addEventListener('click', () => {",
  "  document.getElementById('editModal').close();",
  "});",
  "document.getElementById('close-modal-btn').addEventListener('click', () => {",
  "  document.getElementById('editModal').close();",
  "});",
  "",
  ""
].join('\n');

export function install(env) {
  runLegacyModule(env, source);
}
