export function createGridContext(state) {
  return {
    pb: state.pb,
    gridContainer: state.gridContainer,
    staffGridFilterBar: state.staffGridFilterBar,
    tagFilterSelect: state.tagFilterSelect,
    claimFilterSelect: state.claimFilterSelect,
    similarRequestFilterSelect: state.similarRequestFilterSelect,
    additionalCopyStatusFilterSelect: state.additionalCopyStatusFilterSelect,
    closedTypeFilterSelect: state.closedTypeFilterSelect,
    gridSearchInput: state.gridSearchInput,
    settingsContainer: state.settingsContainer,

    formatMap: state.formatMap,
    ageMap: state.ageMap,
    closeReasonMap: state.closeReasonMap,
    descriptions: state.descriptions,
    emptyStateMessages: state.emptyStateMessages,
    statusStages: state.statusStages,
    rowActionRegistry: state.rowActionRegistry,

    get grid() { return state.grid; },
    get currentStatus() { return state.currentStatus; },
    get currentSuggestions() { return state.currentSuggestions; },
    get allSuggestions() { return state.allSuggestions; },
    get activeTagFilter() { return state.activeTagFilter; },
    get gridSearchKeyword() { return state.gridSearchKeyword; },
    get currentClaimFilter() { return state.currentClaimFilter; },
    get currentSimilarRequestFilter() { return state.currentSimilarRequestFilter; },
    get currentAdditionalCopyStatus() { return state.currentAdditionalCopyStatus; },
    get currentClosedTypeFilter() { return state.currentClosedTypeFilter; },
    get currentWorkflowOrgScopeId() { return state.currentWorkflowOrgScopeId; },
    get workflowSettings() { return state.workflowSettings; },
    get currentSettingsSection() { return state.currentSettingsSection; },
    get activeActionMenu() { return state.activeActionMenu; },

    setCurrentStatus: state.setCurrentStatus,
    setCurrentSuggestions: state.setCurrentSuggestions,
    setActiveTagFilter: state.setActiveTagFilter,
    setGridSearchKeyword: state.setGridSearchKeyword,
    setCurrentClaimFilter: state.setCurrentClaimFilter,
    setCurrentWorkflowOrgScopeId: state.setCurrentWorkflowOrgScopeId,
    setCurrentClosedTypeFilter: state.setCurrentClosedTypeFilter,
    setActiveActionMenu: state.setActiveActionMenu,
    setGrid: state.setGrid,
    setAllSuggestions: state.setAllSuggestions,
    incrementRowActionIdCounter: state.incrementRowActionIdCounter
  };
}
