import { runLegacyModule } from './runtime.js';

const source = [
  "normalizePublicationOptions = function normalizePublicationOptions(options) {",
  "  const raw = Array.isArray(options) ? options : String(options || '').split(/\\r?\\n/);",
  "  const cleaned = raw.map(option => String(option && typeof option === 'object' ? option.label : option || '').trim()).filter(Boolean);",
  "  return cleaned.length ? Array.from(new Set(cleaned)) : defaultPublicationOptions.slice();",
  "}",
  "",
  "normalizeAgeGroups = function normalizeAgeGroups(options) {",
  "  const raw = Array.isArray(options) ? options : String(options || '').split(/\\r?\\n/);",
  "  const cleaned = raw.map(option => String(option && typeof option === 'object' ? option.label : option || '').trim()).filter(Boolean);",
  "  return cleaned.length ? Array.from(new Set(cleaned)) : defaultAgeGroups.slice();",
  "}",
  "",
  "optionIdFromLabel = function optionIdFromLabel(label, fallback = 'option') {",
  "  const id = String(label || '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');",
  "  return id || fallback;",
  "}",
  "",
  "normalizeOptionList = function normalizeOptionList(options, fallbackLabels) {",
  "  const fallback = (fallbackLabels || []).map((label, index) => ({ id: optionIdFromLabel(label, `option_${index + 1}`), label, enabled: true, sortOrder: (index + 1) * 10 }));",
  "  let raw = [];",
  "  if (Array.isArray(options)) raw = options;",
  "  else raw = String(options || '').split(/\\r?\\n/).map(label => ({ label }));",
  "  const seenLabels = new Set();",
  "  const seenIds = new Set();",
  "  const normalized = [];",
  "  raw.forEach((item, index) => {",
  "    const obj = item && typeof item === 'object' ? item : { label: item };",
  "    const label = String(obj.label || obj.value || obj.name || '').trim();",
  "    if (!label || seenLabels.has(label.toLowerCase())) return;",
  "    seenLabels.add(label.toLowerCase());",
  "    let id = String(obj.id || '').trim() || optionIdFromLabel(label, `option_${index + 1}`);",
  "    const baseId = id;",
  "    let suffix = 2;",
  "    while (seenIds.has(id)) id = `${baseId}_${suffix++}`;",
  "    seenIds.add(id);",
  "    normalized.push({ id, label, enabled: obj.enabled !== false, sortOrder: Number(obj.sortOrder || ((index + 1) * 10)) });",
  "  });",
  "  normalized.sort((a, b) => (a.sortOrder || 0) - (b.sortOrder || 0));",
  "  return normalized.length ? normalized : fallback;",
  "}",
  "",
  "enabledOptionLabels = function enabledOptionLabels(options, fallbackLabels) {",
  "  return normalizeOptionList(options, fallbackLabels).filter(option => option.enabled !== false).map(option => option.label);",
  "}",
  "",
  "setPublicationOptions = function setPublicationOptions(options) {",
  "  const normalized = normalizePublicationOptions(options);",
  "  document.querySelectorAll('.publication-options-select').forEach(select => {",
  "    const val = select.value || normalized[0];",
  "    select.innerHTML = '';",
  "    normalized.forEach(opt => {",
  "      const el = document.createElement('option');",
  "      el.value = opt;",
  "      el.textContent = opt;",
  "      select.appendChild(el);",
  "    });",
  "    select.value = normalized.includes(val) ? val : normalized[0];",
  "  });",
  "}",
  "",
  "setAgeGroups = function setAgeGroups(options) {",
  "  const normalized = normalizeAgeGroups(options);",
  "  ['edit-age', 'new-age'].forEach(id => {",
  "    const select = document.getElementById(id);",
  "    if (!select) return;",
  "    const val = select.value || normalized[0];",
  "    select.innerHTML = '';",
  "    normalized.forEach(opt => {",
  "      const el = document.createElement('option');",
  "      el.value = opt;",
  "      el.textContent = opt;",
  "      select.appendChild(el);",
  "    });",
  "    // Try to preserve value, fallback to the first option",
  "    select.value = normalized.includes(val) ? val : normalized[0];",
  "  });",
  "}",
  "",
  "normalizePatronFormatRules = function normalizePatronFormatRules(rules) {",
  "  const normalized = structuredClone(defaultPatronFormatRules);",
  "  const incoming = rules && typeof rules === 'object' ? rules : {};",
  "",
  "  patronFormatKeys.forEach(format => {",
  "    const incomingFormat = incoming[format] || {};",
  "    const behavior = String(incomingFormat.messageBehavior || '').trim();",
  "    if (['none', 'ebookMessage', 'eaudiobookMessage'].includes(behavior)) {",
  "      normalized[format].messageBehavior = behavior;",
  "    }",
  "",
  "    const incomingFields = incomingFormat.fields || {};",
  "    patronFormatFields.forEach(fieldInfo => {",
  "      const field = fieldInfo.key;",
  "      const incomingField = incomingFields[field] || {};",
  "      const defaultField = normalized[format].fields[field];",
  "      let mode = String(incomingField.mode || defaultField.mode || 'optional').trim();",
  "      if (!['required', 'optional', 'hidden'].includes(mode)) mode = defaultField.mode || 'optional';",
  "      if (field === 'title') mode = 'required';",
  "      normalized[format].fields[field] = {",
  "        mode,",
  "        label: String(incomingField.label || defaultField.label || fieldInfo.label).trim() || defaultField.label || fieldInfo.label",
  "      };",
  "    });",
  "  });",
  "",
  "  return normalized;",
  "}",
  "",
  "renderPatronFormatRulesEditor = function renderPatronFormatRulesEditor(rules) {",
  "  const editor = document.getElementById('format-rules-editor');",
  "  if (!editor) return;",
  "",
  "  const normalized = normalizePatronFormatRules(rules);",
  "  editor.innerHTML = patronFormatKeys.map(format => {",
  "    const rule = normalized[format];",
  "    const rows = patronFormatFields.map(fieldInfo => {",
  "      const field = rule.fields[fieldInfo.key];",
  "      const titleLocked = fieldInfo.key === 'title';",
  "      return `",
  "        <tr>",
  "          <td>",
  "            <strong>${escapeAttr(fieldInfo.label)}</strong>",
  "            <div class=\"small text-muted\">Saves to <code>${escapeAttr(fieldInfo.storage)}</code></div>",
  "          </td>",
  "          <td class=\"format-rule-mode-cell\">",
  "            <select class=\"form-control form-control-sm format-rule-mode\" data-format=\"${escapeAttr(format)}\" data-field=\"${escapeAttr(fieldInfo.key)}\"${titleLocked ? ' disabled' : ''}>",
  "              <option value=\"required\"${field.mode === 'required' ? ' selected' : ''}>Required</option>",
  "              <option value=\"optional\"${field.mode === 'optional' ? ' selected' : ''}>Optional</option>",
  "              <option value=\"hidden\"${field.mode === 'hidden' ? ' selected' : ''}>Hidden</option>",
  "            </select>",
  "            ${titleLocked ? '<div class=\"small text-muted\">Title is always required.</div>' : ''}",
  "          </td>",
  "          <td>",
  "            <input type=\"text\" class=\"form-control form-control-sm format-rule-label\" data-format=\"${escapeAttr(format)}\" data-field=\"${escapeAttr(fieldInfo.key)}\" value=\"${escapeAttr(field.label)}\">",
  "          </td>",
  "        </tr>",
  "      `;",
  "    }).join('');",
  "",
  "    return `",
  "      <div class=\"card mb-3\">",
  "        <div class=\"card-header d-flex flex-wrap justify-content-between align-items-center\">",
  "          <strong>${escapeAttr(formatMap[format] || format)}</strong>",
  "          <div class=\"form-inline mt-2 mt-md-0\">",
  "            <label class=\"small text-muted mr-2\" for=\"format-rule-message-${escapeAttr(format)}\">Message behavior</label>",
  "            <select id=\"format-rule-message-${escapeAttr(format)}\" class=\"form-control form-control-sm format-rule-message\" data-format=\"${escapeAttr(format)}\">",
  "              <option value=\"none\"${rule.messageBehavior === 'none' ? ' selected' : ''}>Show fields and allow submission</option>",
  "              <option value=\"ebookMessage\"${rule.messageBehavior === 'ebookMessage' ? ' selected' : ''}>Show eBook message only</option>",
  "              <option value=\"eaudiobookMessage\"${rule.messageBehavior === 'eaudiobookMessage' ? ' selected' : ''}>Show eAudiobook message only</option>",
  "            </select>",
  "          </div>",
  "        </div>",
  "        <div class=\"table-responsive\">",
  "          <table class=\"table table-sm mb-0\">",
  "            <thead>",
  "              <tr>",
  "                <th>Canonical Field</th>",
  "                <th>Mode</th>",
  "                <th>Patron Label</th>",
  "              </tr>",
  "            </thead>",
  "            <tbody>${rows}</tbody>",
  "          </table>",
  "        </div>",
  "      </div>",
  "    `;",
  "  }).join('');",
  "}",
  "",
  "collectPatronFormatRules = function collectPatronFormatRules() {",
  "  const rules = normalizePatronFormatRules(defaultPatronFormatRules);",
  "  const editor = document.getElementById('format-rules-editor');",
  "  if (!editor) return rules;",
  "",
  "  editor.querySelectorAll('.format-rule-message').forEach(select => {",
  "    const format = select.getAttribute('data-format');",
  "    if (rules[format]) rules[format].messageBehavior = select.value;",
  "  });",
  "",
  "  editor.querySelectorAll('.format-rule-mode').forEach(select => {",
  "    const format = select.getAttribute('data-format');",
  "    const field = select.getAttribute('data-field');",
  "    if (rules[format] && rules[format].fields[field]) {",
  "      rules[format].fields[field].mode = field === 'title' ? 'required' : select.value;",
  "    }",
  "  });",
  "",
  "  editor.querySelectorAll('.format-rule-label').forEach(input => {",
  "    const format = input.getAttribute('data-format');",
  "    const field = input.getAttribute('data-field');",
  "    if (rules[format] && rules[format].fields[field]) {",
  "      rules[format].fields[field].label = input.value.trim() || rules[format].fields[field].label;",
  "    }",
  "  });",
  "",
  "  return normalizePatronFormatRules(rules);",
  "}",
  "",
  "setPublicationOptions = function setPublicationOptions(options) {",
  "  publicationOptions = normalizePublicationOptions(options);",
  "  document.querySelectorAll('.publication-options-select').forEach(select => {",
  "    populatePublicationSelect(select, select.value);",
  "  });",
  "}",
  "",
  "populatePublicationSelect = function populatePublicationSelect(select, selectedValue) {",
  "  if (!select) return;",
  "  const selected = selectedValue || select.value || publicationOptions[0];",
  "  select.innerHTML = '';",
  "  publicationOptions.forEach(option => {",
  "    const item = document.createElement('option');",
  "    item.value = option;",
  "    item.textContent = option;",
  "    select.appendChild(item);",
  "  });",
  "  setSelectValue(select, selected);",
  "}",
  "",
  "setSelectValue = function setSelectValue(select, value) {",
  "  if (!select) return;",
  "  value = String(value || '').trim();",
  "  if (value && !publicationOptions.includes(value)) {",
  "    const item = document.createElement('option');",
  "    item.value = value;",
  "    item.textContent = value;",
  "    select.appendChild(item);",
  "  }",
  "  select.value = value || publicationOptions[0] || '';",
  "}",
  "",
  "renderOptionListEditor = function renderOptionListEditor(editorId, options, fallbackLabels) {",
  "  const editor = document.getElementById(editorId);",
  "  if (!editor) return;",
  "  const list = normalizeOptionList(options, fallbackLabels);",
  "  editor.innerHTML = list.map((option, index) => `",
  "    <div class=\"option-list-row\" data-option-id=\"${escapeAttr(option.id)}\">",
  "      <input type=\"text\" class=\"form-control form-control-sm option-list-label\" value=\"${escapeAttr(option.label)}\" aria-label=\"Option label\">",
  "      <div class=\"form-check mb-0\">",
  "        <input type=\"checkbox\" class=\"form-check-input option-list-enabled\" id=\"${escapeAttr(editorId)}-${escapeAttr(option.id)}\"${option.enabled !== false ? ' checked' : ''}>",
  "        <label class=\"form-check-label small\" for=\"${escapeAttr(editorId)}-${escapeAttr(option.id)}\">Enabled</label>",
  "      </div>",
  "      <button type=\"button\" class=\"btn btn-sm btn-outline-secondary option-list-up\"${index === 0 ? ' disabled' : ''} aria-label=\"Move up\">Up</button>",
  "      <button type=\"button\" class=\"btn btn-sm btn-outline-secondary option-list-down\"${index === list.length - 1 ? ' disabled' : ''} aria-label=\"Move down\">Down</button>",
  "      <button type=\"button\" class=\"btn btn-sm btn-outline-danger option-list-delete\" aria-label=\"Delete option\">Delete</button>",
  "    </div>",
  "  `).join('');",
  "}",
  "",
  "collectOptionList = function collectOptionList(editorId, fallbackLabels) {",
  "  const editor = document.getElementById(editorId);",
  "  if (!editor) return normalizeOptionList([], fallbackLabels);",
  "  const seen = new Set();",
  "  const rows = Array.from(editor.querySelectorAll('.option-list-row'));",
  "  const options = rows.map((row, index) => {",
  "    const input = row.querySelector('.option-list-label');",
  "    const label = input ? input.value.trim() : '';",
  "    if (!label) return null;",
  "    const key = label.toLowerCase();",
  "    if (seen.has(key)) throw new Error('Option labels must be unique within each list.');",
  "    seen.add(key);",
  "    const existingId = row.getAttribute('data-option-id') || '';",
  "    return {",
  "      id: existingId || optionIdFromLabel(label, `option_${index + 1}`),",
  "      label,",
  "      enabled: !!row.querySelector('.option-list-enabled')?.checked,",
  "      sortOrder: (index + 1) * 10",
  "    };",
  "  }).filter(Boolean);",
  "  if (!options.length) throw new Error('Each option list must include at least one label.');",
  "  return options;",
  "}",
  "",
  "addOptionListRow = function addOptionListRow(editorId, fallbackLabels) {",
  "  const current = collectOptionList(editorId, fallbackLabels);",
  "  let base = 'New option';",
  "  let label = base;",
  "  let i = 2;",
  "  const labels = new Set(current.map(option => option.label.toLowerCase()));",
  "  while (labels.has(label.toLowerCase())) label = `${base} ${i++}`;",
  "  current.push({ id: optionIdFromLabel(label, `option_${current.length + 1}`), label, enabled: true, sortOrder: (current.length + 1) * 10 });",
  "  renderOptionListEditor(editorId, current, fallbackLabels);",
  "  markSettingsDirty();",
  "}",
  "",
  "handleOptionListClick = function handleOptionListClick(event) {",
  "  const button = event.target.closest('button');",
  "  if (!button) return;",
  "  const editor = event.target.closest('.option-list-editor');",
  "  if (!editor) return;",
  "  const row = button.closest('.option-list-row');",
  "  if (!row) return;",
  "  const fallback = editor.id === 'ui-age-groups-editor' ? defaultAgeGroups : defaultPublicationOptions;",
  "  const list = collectOptionList(editor.id, fallback);",
  "  const index = Array.from(editor.querySelectorAll('.option-list-row')).indexOf(row);",
  "  if (button.classList.contains('option-list-up') && index > 0) {",
  "    [list[index - 1], list[index]] = [list[index], list[index - 1]];",
  "  } else if (button.classList.contains('option-list-down') && index < list.length - 1) {",
  "    [list[index + 1], list[index]] = [list[index], list[index + 1]];",
  "  } else if (button.classList.contains('option-list-delete')) {",
  "    if (list.length <= 1) throw new Error('Each option list must include at least one label.');",
  "    list.splice(index, 1);",
  "  } else {",
  "    return;",
  "  }",
  "  list.forEach((option, nextIndex) => option.sortOrder = (nextIndex + 1) * 10);",
  "  renderOptionListEditor(editor.id, list, fallback);",
  "  markSettingsDirty();",
  "}",
  "",
  "document.getElementById('btn-bib-lookup').addEventListener('click', async () => {",
  "  const bibId = document.getElementById('edit-bibid').value.trim();",
  "  const btn = document.getElementById('btn-bib-lookup');",
  "  const display = document.getElementById('bib-info-display');",
  "  const text = document.getElementById('bib-info-text');",
  "",
  "  if (!bibId) {",
  "    display.classList.remove('hidden', 'alert-info');",
  "    display.classList.add('alert-danger');",
  "    text.textContent = 'Please enter a BIB ID first.';",
  "    return;",
  "  }",
  "",
  "  btn.disabled = true;",
  "  btn.textContent = '...';",
  "  display.classList.add('hidden');",
  "",
  "  try {",
  "    const row = currentSuggestions.find(r => r.id === document.getElementById('edit-id').value);",
  "    const barcode = row ? row.barcode : '';",
  "",
  "    const res = await fetch('/api/asap/staff/bib-lookup', {",
  "      method: 'POST',",
  "      headers: {",
  "        'Content-Type': 'application/json',",
  "        'Authorization': pb.authStore.token",
  "      },",
  "      body: JSON.stringify({ bibId, barcode })",
  "    });",
  "    const data = await res.json();",
  "    if (!res.ok) throw new Error(data.message || 'Lookup failed');",
  "",
  "    display.classList.remove('hidden', 'alert-danger', 'alert-warning');",
  "    display.classList.add('alert-info');",
  "",
  "    let infoText = (data.title || 'No title') + (data.author ? ' by ' + data.author : '');",
  "",
  "    // Update title and author fields if they don't match the bib data",
  "    const titleInput = document.getElementById('edit-title');",
  "    const authorInput = document.getElementById('edit-author');",
  "",
  "    if (data.title) {",
  "      const oldTitle = titleInput.value.trim();",
  "      const pTitle = data.title.trim();",
  "      if (pTitle && oldTitle !== pTitle && oldTitle.indexOf(pTitle + \" (\") !== 0) {",
  "        titleInput.value = pTitle + \" (\" + oldTitle + \")\";",
  "      }",
  "    }",
  "",
  "    if (data.author) {",
  "      const oldAuthor = authorInput.value.trim();",
  "      const pAuthor = data.author.trim();",
  "      if (pAuthor && oldAuthor !== pAuthor && oldAuthor.indexOf(pAuthor + \" (\") !== 0) {",
  "        authorInput.value = pAuthor + \" (\" + oldAuthor + \")\";",
  "      }",
  "    }",
  "",
  "    // Check for duplicate hold in Polaris",
  "    if (data.patronHoldCheck && data.patronHoldCheck.statusValue === 29) {",
  "      display.classList.remove('alert-info');",
  "      display.classList.add('alert-warning');",
  "      infoText = \"DUPLICATE: Patron already has a hold on this item in Polaris. \" + infoText;",
  "    }",
  "",
  "    text.textContent = infoText;",
  "    verifiedBibId = bibId;",
  "  } catch (err) {",
  "    display.classList.remove('hidden', 'alert-info');",
  "    display.classList.add('alert-danger');",
  "    text.textContent = 'Error: ' + err.message;",
  "    verifiedBibId = '';",
  "  } finally {",
  "    btn.disabled = false;",
  "    btn.textContent = 'Lookup BIB';",
  "  }",
  "});",
  "",
  "dateOnly = function dateOnly(value) {",
  "  value = String(value || '').trim();",
  "  return value ? value.split(' ')[0].split('T')[0] : '';",
  "}",
  "",
  "collectSettingsPolaris = function collectSettingsPolaris() {",
  "  return {",
  "    host: getFieldValue('polaris-host'),",
  "    apiKey: getFieldValue('polaris-api-key'),",
  "    accessId: getFieldValue('polaris-access-id'),",
  "    staffDomain: getFieldValue('polaris-domain'),",
  "    adminUser: getFieldValue('polaris-admin-user'),",
  "    adminPassword: getFieldValue('polaris-admin-pass'),",
  "    overridePassword: getFieldValue('polaris-override-pass'),",
  "    autoPromote: getFieldChecked('polaris-auto-promote'),",
  "    langId: \"1033\",",
  "    appId: \"100\",",
  "    orgId: \"1\",",
  "    pickupOrgId: \"0\",",
  "    requestingOrgId: \"3\",",
  "    workstationId: \"1\",",
  "    userId: \"1\"",
  "  };",
  "}",
  "",
  "document.getElementById('btn-test-polaris').addEventListener('click', async (e) => {",
  "  e.preventDefault();",
  "  const resSpan = document.getElementById('polaris-test-result');",
  "  const btn = e.currentTarget;",
  "  const polarisPayload = collectSettingsPolaris();",
  "",
  "  if (!polarisPayload.host || !polarisPayload.accessId || !polarisPayload.apiKey) {",
  "    setInlineResult(resSpan, 'Enter the Polaris host, PAPI access ID, and PAPI API key before testing.', 'ml-2 text-danger font-weight-bold');",
  "    return;",
  "  }",
  "",
  "  const saved = await saveSettings({",
  "    button: btn,",
  "    pendingText: 'Saving before Polaris test...',",
  "    successText: 'Settings saved. Testing Polaris...',",
  "    clearDelay: 0",
  "  });",
  "  if (!saved) {",
  "    setInlineResult(resSpan, 'Error: settings could not be saved.', 'ml-2 text-danger font-weight-bold');",
  "    return;",
  "  }",
  "",
  "  await postPolarisTest('/api/asap/staff/test-polaris', resSpan, { polaris: polarisPayload }, {",
  "    button: btn,",
  "    token: pb.authStore.token,",
  "    pendingText: 'Saving and testing...',",
  "    pendingClass: 'ml-2 text-muted',",
  "    successClass: 'ml-2 text-success font-weight-bold',",
  "    errorClass: 'ml-2 text-danger font-weight-bold',",
  "    successText: 'Success! Polaris API is working.'",
  "  });",
  "});",
  "",
  "const syncOrganizationsBtn = document.getElementById('btn-sync-organizations');",
  "syncPolarisOrganizations = async function syncPolarisOrganizations(options = {}) {",
  "  const resultEl = document.getElementById('organizations-sync-result');",
  "  const btn = options.button || syncOrganizationsBtn;",
  "  if (btn) btn.disabled = true;",
  "  setOrganizationsStatus('loading', 'Organizations loading from Polaris. Organization selection will be available after this sync completes.');",
  "  setInlineResult(resultEl, 'Syncing organizations...', 'ml-2 text-muted');",
  "",
  "  try {",
  "    const result = await authorizedJson('/api/asap/staff/organizations/sync', { method: 'POST' });",
  "    const count = result.synced || 0;",
  "    setOrganizationsStatus('loaded', `Polaris organizations loaded successfully. ${count} organization record${count === 1 ? '' : 's'} synced. Leave all libraries unchecked to enable all organizations.`);",
  "    setInlineResult(resultEl, `Synced ${count} organization records.`, 'ml-2 text-success font-weight-bold');",
  "    const container = document.getElementById('enabled-libraries-checkbox-container');",
  "    if (container) {",
  "      container.removeAttribute('data-loaded');",
  "    }",
  "    if (isSuperAdminStaff()) {",
  "      await populateLibrarySelector();",
  "    }",
  "    await renderLibraryParticipationCheckboxes();",
  "    return result;",
  "  } catch (err) {",
  "    setOrganizationsStatus('error', 'Polaris connected, but organizations could not be loaded. Some setup options may be unavailable until this sync succeeds.');",
  "    setInlineResult(resultEl, 'Warning: ' + (err.message || 'Organization sync failed.'), 'ml-2 text-warning font-weight-bold');",
  "    throw err;",
  "  } finally {",
  "    if (btn) btn.disabled = false;",
  "  }",
  "}",
  "",
  "if (syncOrganizationsBtn) {",
  "  syncOrganizationsBtn.addEventListener('click', async (e) => {",
  "    e.preventDefault();",
  "    try {",
  "      await syncPolarisOrganizations({ button: syncOrganizationsBtn });",
  "    } catch (err) {",
  "      // syncPolarisOrganizations already updates the visible warning state.",
  "    }",
  "  });",
  "}",
  "",
  "document.getElementById('btn-run-hold-check').addEventListener('click', async () => {",
  "  const btn = document.getElementById('btn-run-hold-check');",
  "  const msg = document.getElementById('job-msg');",
  "",
  "  btn.disabled = true;",
  "  msg.textContent = 'Running hold check...';",
  "  msg.className = 'mb-3 font-weight-bold text-info';",
  "",
  "  try {",
  "    const res = await fetch('/api/asap/jobs/hold-check', {",
  "      method: 'POST',",
  "      headers: { 'Authorization': pb.authStore.token }",
  "    });",
  "    const data = await res.json();",
  "    if (res.ok) {",
  "      msg.textContent = `Hold check complete. Moved to Pending hold: ${data.promoted}, holds placed: ${data.holdsPlaced}, closed after checkout: ${data.checkoutClosures}, auto-closed: ${data.timedOut}`;",
  "      msg.className = 'mb-3 font-weight-bold text-success';",
  "      loadTab(currentStatus);",
  "    } else {",
  "      throw new Error(data.message || 'Failed to run hold check');",
  "    }",
  "  } catch (err) {",
  "    msg.textContent = 'Error: ' + err.message;",
  "    msg.className = 'mb-3 font-weight-bold text-danger';",
  "  } finally {",
  "    btn.disabled = false;",
  "  }",
  "});",
  "",
  "document.getElementById('btn-run-promoter-check').addEventListener('click', async () => {",
  "  const btn = document.getElementById('btn-run-promoter-check');",
  "  const msg = document.getElementById('job-msg');",
  "",
  "  btn.disabled = true;",
  "  msg.textContent = 'Running auto-promoter...';",
  "  msg.className = 'mb-3 font-weight-bold text-info';",
  "",
  "  try {",
  "    const res = await fetch('/api/asap/jobs/promoter-check', {",
  "      method: 'POST',",
  "      headers: { 'Authorization': pb.authStore.token }",
  "    });",
  "    const data = await res.json();",
  "    if (res.ok) {",
  "      msg.textContent = `Auto-promoter complete. Moved ${data.promoted} item${data.promoted === 1 ? '' : 's'} to Pending hold.`;",
  "      msg.className = 'mb-3 font-weight-bold text-success';",
  "      loadTab(currentStatus);",
  "    } else {",
  "      throw new Error(data.message || 'Failed to run promoter check');",
  "    }",
  "  } catch (err) {",
  "    msg.textContent = 'Error: ' + err.message;",
  "    msg.className = 'mb-3 font-weight-bold text-danger';",
  "  } finally {",
  "    btn.disabled = false;",
  "  }",
  "});",
  "",
  "const deleteClosedRequestsBtn = document.getElementById('btn-delete-closed-requests');",
  "const bulkDeleteClosedDialog = document.getElementById('bulk-delete-closed-dialog');",
  "const bulkDeleteClosedForm = document.getElementById('bulk-delete-closed-form');",
  "const bulkDeleteClosedInput = document.getElementById('bulk-delete-closed-confirm');",
  "const bulkDeleteClosedSubmit = document.getElementById('bulk-delete-closed-submit');",
  "const bulkDeleteClosedCancel = document.getElementById('bulk-delete-closed-cancel');",
  "const bulkDeleteClosedMsg = document.getElementById('bulk-delete-closed-msg');",
  "",
  "if (deleteClosedRequestsBtn && bulkDeleteClosedDialog) {",
  "  deleteClosedRequestsBtn.addEventListener('click', () => {",
  "    if (!isAdminStaff()) return;",
  "    if (bulkDeleteClosedInput) bulkDeleteClosedInput.value = '';",
  "    if (bulkDeleteClosedSubmit) bulkDeleteClosedSubmit.disabled = true;",
  "    if (bulkDeleteClosedMsg) bulkDeleteClosedMsg.textContent = '';",
  "    bulkDeleteClosedDialog.showModal();",
  "    if (bulkDeleteClosedInput) bulkDeleteClosedInput.focus();",
  "  });",
  "}",
  "",
  "if (bulkDeleteClosedInput && bulkDeleteClosedSubmit) {",
  "  bulkDeleteClosedInput.addEventListener('input', () => {",
  "    bulkDeleteClosedSubmit.disabled = bulkDeleteClosedInput.value !== 'DELETE';",
  "  });",
  "}",
  "",
  "if (bulkDeleteClosedCancel && bulkDeleteClosedDialog) {",
  "  bulkDeleteClosedCancel.addEventListener('click', () => {",
  "    if (bulkDeleteClosedDialog.open) bulkDeleteClosedDialog.close();",
  "  });",
  "}",
  "",
  "if (bulkDeleteClosedForm) {",
  "  bulkDeleteClosedForm.addEventListener('submit', async (e) => {",
  "    e.preventDefault();",
  "    if (!isAdminStaff() || !bulkDeleteClosedSubmit || !bulkDeleteClosedInput) return;",
  "    bulkDeleteClosedSubmit.disabled = true;",
  "    if (bulkDeleteClosedMsg) {",
  "      bulkDeleteClosedMsg.textContent = 'Deleting closed requests...';",
  "      bulkDeleteClosedMsg.className = 'mb-3 font-weight-bold text-info';",
  "    }",
  "    try {",
  "      const result = await authorizedJson('/api/asap/staff/requests/delete-closed', {",
  "        method: 'POST',",
  "        body: JSON.stringify({ confirm: bulkDeleteClosedInput.value })",
  "      });",
  "      if (bulkDeleteClosedDialog && bulkDeleteClosedDialog.open) bulkDeleteClosedDialog.close();",
  "      showToast(`Deleted ${result.deleted || 0} closed request${result.deleted === 1 ? '' : 's'}.`, 'success');",
  "      loadTab('closed');",
  "    } catch (err) {",
  "      if (bulkDeleteClosedMsg) {",
  "        bulkDeleteClosedMsg.textContent = err.message || 'Could not delete closed requests.';",
  "        bulkDeleteClosedMsg.className = 'mb-3 font-weight-bold text-danger';",
  "      }",
  "      bulkDeleteClosedSubmit.disabled = bulkDeleteClosedInput.value !== 'DELETE';",
  "    }",
  "  });",
  "}",
  "",
  "document.getElementById('btn-test-smtp').addEventListener('click', async (e) => {",
  "  e.preventDefault();",
  "  const resSpan = document.getElementById('smtp-test-result');",
  "  const testInput = document.getElementById('smtp-test-email');",
  "  const btn = e.currentTarget;",
  "",
  "  const testEmail = testInput ? testInput.value.trim() : '';",
  "  const smtpHost = getFieldValue('smtp-host').trim();",
  "  const sender = getFieldValue('smtp-from').trim() || getFieldValue('email-from-address').trim();",
  "",
  "  if (!smtpHost || !sender || !testEmail) {",
  "    resSpan.textContent = 'Enter SMTP host, sender address, and test recipient before testing SMTP.';",
  "    resSpan.className = 'mt-2 text-danger font-weight-bold small';",
  "    return;",
  "  }",
  "  if (!validateSmtpHostField(true)) {",
  "    return;",
  "  }",
  "",
  "  resSpan.textContent = \"Saving and testing...\";",
  "  resSpan.className = \"mt-2 text-muted small\";",
  "",
  "  const saved = await saveSettings({",
  "    button: btn,",
  "    pendingText: 'Saving settings...',",
  "    successText: 'Settings saved. Testing SMTP...',",
  "    clearDelay: 0",
  "  });",
  "  if (!saved) {",
  "    resSpan.textContent = \"Error: settings could not be saved.\";",
  "    resSpan.className = \"mt-2 text-danger font-weight-bold small\";",
  "    return;",
  "  }",
  "",
  "  try {",
  "    // Give PocketBase hooks a brief moment to apply freshly saved SMTP settings",
  "    // before issuing the test request.",
  "    await new Promise(resolve => setTimeout(resolve, 300));",
  "",
  "    const res = await fetch('/api/asap/staff/test-smtp', {",
  "      method: 'POST',",
  "      headers: {",
  "        'Authorization': pb.authStore.token,",
  "        'Content-Type': 'application/json'",
  "      },",
  "      body: JSON.stringify({ email: testEmail })",
  "    });",
  "    const data = await res.json();",
  "    if (res.ok && data.success) {",
  "      resSpan.textContent = \"Success! \" + data.message;",
  "      resSpan.className = \"mt-2 text-success font-weight-bold small\";",
  "    } else {",
  "      resSpan.textContent = \"Error: \" + (data.message || \"Failed\");",
  "      resSpan.className = \"mt-2 text-danger font-weight-bold small\";",
  "    }",
  "  } catch (err) {",
  "    resSpan.textContent = \"Error testing SMTP.\";",
  "    resSpan.className = \"mt-2 text-danger font-weight-bold small\";",
  "  }",
  "});",
  "",
  "showSettingsAccessDenied = function showSettingsAccessDenied() {",
  "  settingsContainer.classList.remove('hidden');",
  "  setVisible('settings-error', true);",
  "  const formEl = document.getElementById('settings-form');",
  "  if (formEl) formEl.classList.add('hidden');",
  "}",
  "",
  "hideSettingsAccessDenied = function hideSettingsAccessDenied() {",
  "  setVisible('settings-error', false);",
  "}",
  "",
  "loadSettings = async function loadSettings(options = {}) {",
  "  const isSuper = isSuperAdminStaff();",
  "  const showErrors = options.showErrors !== false;",
  "  settingsLoading = true;",
  "",
  "  try {",
  "    // Filter sidebar for non-super admins",
  "    document.querySelectorAll('[data-settings-target]').forEach(el => {",
  "      const section = el.getAttribute('data-settings-target');",
  "      // Allow library admins to see settings they can override",
  "      const allowedForAdmins = ['templates', 'workflow', 'patron'];",
  "      if (!isSuper && !allowedForAdmins.includes(section)) {",
  "        el.classList.add('hidden');",
  "      } else {",
  "        el.classList.remove('hidden');",
  "      }",
  "    });",
  "",
  "    // If not super admin, force them to an allowed section if they are on a hidden one",
  "    const allowedForAdmins = ['templates', 'workflow', 'patron'];",
  "    if (!isSuper && !allowedForAdmins.includes(currentSettingsSection)) {",
  "      activateSettingsSection('templates', { updateHash: true });",
  "    }",
  "",
  "    // Load Library Selector for Super Admins",
  "    if (isSuper) {",
  "      await populateLibrarySelector();",
  "      document.getElementById('super-admin-library-selector').classList.remove('hidden');",
  "    } else {",
  "      document.getElementById('super-admin-library-selector').classList.add('hidden');",
  "      currentLibraryContextOrgId = pb.authStore.model.libraryOrgId || 'system';",
  "      const libraryName = pb.authStore.model.libraryOrgName || 'My Library';",
  "      document.getElementById('library-context-display').textContent = currentLibraryContextOrgId === 'system'",
  "        ? libraryName",
  "        : `${libraryName} (ID ${currentLibraryContextOrgId})`;",
  "    }",
  "",
  "    const loadedLibrarySettings = await loadLibrarySettings(currentLibraryContextOrgId);",
  "",
  "    if (!isSuper) {",
  "      // Hide error, show form for library admins even if they can't load system-scoped settings.",
  "      hideSettingsAccessDenied();",
  "      const formEl = document.getElementById('settings-form');",
  "      if (formEl) formEl.classList.remove('hidden');",
  "      return;",
  "    }",
  "",
  "    const smtp = (loadedLibrarySettings && loadedLibrarySettings.smtp) || {};",
  "    const polaris = (loadedLibrarySettings && loadedLibrarySettings.polaris) || {};",
  "    const emails = (loadedLibrarySettings && loadedLibrarySettings.emails) || {};",
  "",
  "    const hasPolarisCredentials = !!(polaris.host && polaris.apiKey && polaris.accessId && polaris.staffDomain && polaris.adminUser && polaris.adminPassword);",
  "    if (hasPolarisCredentials && (organizationsStatus === 'not_loaded' || organizationsStatus === 'error')) {",
  "      syncPolarisOrganizations().catch(() => {",
  "        // syncPolarisOrganizations updates the visible warning state.",
  "      });",
  "    }",
  "",
  "    workflowSettings.outstandingTimeoutEnabled = !!((loadedLibrarySettings && loadedLibrarySettings.workflow || {}).outstandingTimeoutEnabled);",
  "    workflowSettings.outstandingTimeoutDays = parseInt(((loadedLibrarySettings && loadedLibrarySettings.workflow || {}).outstandingTimeoutDays) || '30', 10) || 30;",
  "    workflowSettings.autoPromote = polaris.autoPromote !== false;",
  "",
  "    // Workflow form population is handled by loadLibrarySettings",
  "",
  "    // SMTP",
  "    setFieldValue('smtp-host', smtp.host || '');",
  "    setFieldValue('smtp-port', smtp.port || 587);",
  "    setFieldValue('smtp-username', smtp.username || '');",
  "    setFieldValue('smtp-password', smtp.password || '');",
  "    setFieldChecked('smtp-tls', smtp.tls !== false);",
  "",
  "    // Also populate the duplicate SMTP fields with the emails value",
  "    setFieldValue('smtp-from', emails.fromAddress || '');",
  "    setFieldValue('smtp-from-name', emails.fromName || '');",
  "",
  "    // Polaris",
  "    setFieldValue('polaris-host', polaris.host || '');",
  "    setFieldValue('polaris-api-key', polaris.apiKey || '');",
  "    setFieldValue('polaris-access-id', polaris.accessId || '');",
  "    setFieldValue('polaris-domain', polaris.staffDomain || '');",
  "    setFieldValue('polaris-admin-user', polaris.adminUser || '');",
  "    setFieldValue('polaris-admin-pass', polaris.adminPassword || '');",
  "    setFieldValue('polaris-override-pass', polaris.overridePassword || '');",
  "    setFieldChecked('polaris-auto-promote', polaris.autoPromote !== false);",
  "",
  "    // UI Text and Formats are handled by populatePatronUiForms called via loadLibrarySettings",
  "    // but we can set them here if needed. Since loadLibrarySettings is called right before this, ",
  "    // it will be populated. Wait, loadLibrarySettings is called AT THE TOP of loadSettings asynchronously!",
  "    // So if it completes before loadSettings finishes, loadSettings might overwrite it?",
  "    // Actually, loadLibrarySettings is awaited at the top. So we should just remove the uiText Population from loadSettings and let loadLibrarySettings handle it.",
  "    await populateStaffLibraryOptions();",
  "    await loadStaffUsers();",
  "",
  "",
  "",
  "    // Success: hide error, show form",
  "    hideSettingsAccessDenied();",
  "    const formEl = document.getElementById('settings-form');",
  "    if (formEl) formEl.classList.remove('hidden');",
  "",
  "  } catch (err) {",
  "    if (isPocketBaseAutoCancelError(err)) {",
  "      return;",
  "    }",
  "    console.error('Failed to load settings', err);",
  "    if (showErrors) {",
  "      showSettingsAccessDenied();",
  "    }",
  "  } finally {",
  "    settingsLoading = false;",
  "    markSettingsClean('clean');",
  "  }",
  "}",
  "",
  "const emailTemplateDefaults = {",
  "  suggestion_submitted: {",
  "    subject: 'Suggestion received: {{title}}',",
  "    body: 'Hello {{name}},\\n\\nThank you for suggesting {{title}} by {{author}} in {{format}} format. Our collection development team has received your request and will review it.\\n\\nIf we add this item, we will place a hold for you automatically and send another update.\\n\\nThank you for helping us shape the library collection.'",
  "  },",
  "  already_owned: {",
  "    subject: '{{title}} is already available',",
  "    body: 'Hello {{name}},\\n\\nThank you for suggesting {{title}} by {{author}} in {{format}} format.\\n\\nThe library already owns this title or has it on order. We have placed a hold on card {{barcode}} so you will be notified when it is ready.\\n\\nThank you for using the library\\'s suggestion service.'",
  "  },",
  "  rejected: {",
  "    subject: 'Update on your suggestion: {{title}}',",
  "    body: 'Hello {{name}},\\n\\nThank you for suggesting {{title}} by {{author}} in {{format}} format.\\n\\nAfter review, we are not able to add this item to the collection at this time. We appreciate you taking the time to share your suggestion with us.\\n\\nThank you for helping us build a collection that reflects our community.'",
  "  },",
  "  hold_placed: {",
  "    subject: 'Hold placed for {{title}}',",
  "    body: 'Hello {{name}},\\n\\nGood news. The library plans to add {{title}} by {{author}} in {{format}} format.\\n\\nWe have placed a hold on card {{barcode}}. You will receive the usual pickup notice when the item is ready.\\n\\nThank you for your suggestion.'",
  "  }",
  "};",
  "",
  "const templateFieldIds = [",
  "  'email-submit-subject',",
  "  'email-submit-body',",
  "  'email-owned-subject',",
  "  'email-owned-body',",
  "  'email-rejected-subject',",
  "  'email-rejected-body',",
  "  'email-hold-subject',",
  "  'email-hold-body'",
  "];",
  "",
  "setTemplateInputsDisabled = function setTemplateInputsDisabled(disabled) {",
  "  templateFieldIds.forEach(id => {",
  "    const field = document.getElementById(id);",
  "    if (field) field.disabled = disabled;",
  "  });",
  "}",
  "",
  "clearTemplateInputs = function clearTemplateInputs() {",
  "  templateFieldIds.forEach(id => {",
  "    const field = document.getElementById(id);",
  "    if (field) field.value = '';",
  "  });",
  "}",
  "",
  "setTemplateStatus = function setTemplateStatus(message, className, hidden = false) {",
  "  const statusAlert = document.getElementById('library-override-status');",
  "  if (!statusAlert) return;",
  "  statusAlert.className = className || 'alert alert-warning mb-4';",
  "  statusAlert.textContent = message || '';",
  "  statusAlert.classList.toggle('hidden', hidden);",
  "}",
  "",
  "populateEmailTemplateForms = function populateEmailTemplateForms(emails) {",
  "  emails = emails || {};",
  "",
  "  if (document.getElementById('email-from-address')) document.getElementById('email-from-address').value = emails.fromAddress || '';",
  "  if (document.getElementById('email-from-name')) document.getElementById('email-from-name').value = emails.fromName || '';",
  "",
  "  // Sync to SMTP tab if we are modifying the system context",
  "  if (currentLibraryContextOrgId === 'system') {",
  "    if (document.getElementById('smtp-from')) document.getElementById('smtp-from').value = emails.fromAddress || '';",
  "    if (document.getElementById('smtp-from-name')) document.getElementById('smtp-from-name').value = emails.fromName || '';",
  "  }",
  "",
  "  const emailSubmit = emails.suggestion_submitted || {};",
  "  if (document.getElementById('email-submit-subject')) document.getElementById('email-submit-subject').value = emailSubmit.subject || emailTemplateDefaults.suggestion_submitted.subject;",
  "  if (document.getElementById('email-submit-body')) document.getElementById('email-submit-body').value = emailSubmit.body || emailTemplateDefaults.suggestion_submitted.body;",
  "",
  "  const emailOwned = emails.already_owned || {};",
  "  if (document.getElementById('email-owned-subject')) document.getElementById('email-owned-subject').value = emailOwned.subject || emailTemplateDefaults.already_owned.subject;",
  "  if (document.getElementById('email-owned-body')) document.getElementById('email-owned-body').value = emailOwned.body || emailTemplateDefaults.already_owned.body;",
  "",
  "  const emailRejected = emails.rejected || {};",
  "  if (document.getElementById('email-rejected-subject')) document.getElementById('email-rejected-subject').value = emailRejected.subject || emailTemplateDefaults.rejected.subject;",
  "  if (document.getElementById('email-rejected-body')) document.getElementById('email-rejected-body').value = emailRejected.body || emailTemplateDefaults.rejected.body;",
  "",
  "  currentRejectionTemplates = Array.isArray(emails.rejection_templates) ? JSON.parse(JSON.stringify(emails.rejection_templates)) : [];",
  "  renderRejectionTemplates();",
  "",
  "  const emailHold = emails.hold_placed || {};",
  "  if (document.getElementById('email-hold-subject')) document.getElementById('email-hold-subject').value = emailHold.subject || emailTemplateDefaults.hold_placed.subject;",
  "  if (document.getElementById('email-hold-body')) document.getElementById('email-hold-body').value = emailHold.body || emailTemplateDefaults.hold_placed.body;",
  "}",
  "",
  "populateLibrarySelector = async function populateLibrarySelector() {",
  "  const select = document.getElementById('select-library-context');",
  "  if (!select) return;",
  "",
  "  try {",
  "    const selectedOrgId = currentLibraryContextOrgId || select.value || 'system';",
  "    select.disabled = true;",
  "    select.innerHTML = '<option value=\"system\">System Defaults</option>';",
  "",
  "    const orgs = await pb.collection('polaris_organizations').getFullList({",
  "      filter: 'organizationCodeId = \"2\"',",
  "      sort: 'displayName',",
  "      requestKey: 'polaris-orgs-library-selector'",
  "    });",
  "",
  "    orgs.forEach(org => {",
  "      const opt = document.createElement('option');",
  "      opt.value = org.organizationId;",
  "      opt.textContent = `${org.displayName || org.name} (ID ${org.organizationId})`;",
  "      select.appendChild(opt);",
  "    });",
  "",
  "    select.value = Array.from(select.options).some(option => option.value === selectedOrgId) ? selectedOrgId : 'system';",
  "    currentLibraryContextOrgId = select.value;",
  "    const selectedOption = select.options[select.selectedIndex];",
  "    if (selectedOption) {",
  "      document.getElementById('library-context-display').textContent = selectedOption.text;",
  "    }",
  "",
  "    if (!librarySelectorBound) {",
  "      select.addEventListener('change', async (e) => {",
  "        const nextOrgId = e.target.value || 'system';",
  "        const previousOrgId = currentLibraryContextOrgId || 'system';",
  "        if (settingsDirty) {",
  "          const proceed = await showConfirm('Unsaved changes', 'You have unsaved changes. Switch libraries without saving?');",
  "          if (!proceed) {",
  "            e.target.value = previousOrgId;",
  "            return;",
  "          }",
  "        }",
  "        currentLibraryContextOrgId = nextOrgId;",
  "        const display = e.target.options[e.target.selectedIndex].text;",
  "        document.getElementById('library-context-display').textContent = display;",
  "        await loadLibrarySettings(currentLibraryContextOrgId);",
  "        markSettingsClean('clean');",
  "      });",
  "      librarySelectorBound = true;",
  "    }",
  "  } catch (err) {",
  "    if (!isPocketBaseAutoCancelError(err)) {",
  "      console.error('Failed to populate library selector', err);",
  "    }",
  "  } finally {",
  "    select.disabled = false;",
  "  }",
  "}",
  "",
  "loadLibrarySettings = async function loadLibrarySettings(orgId) {",
  "  const requestedOrgId = orgId || 'system';",
  "  const requestId = ++libraryContextLoadSerial;",
  "  currentLibraryContextOrgId = requestedOrgId;",
  "",
  "  try {",
  "    let settings = {};",
  "    let isOverride = false;",
  "",
  "    const result = await authorizedJson(`/api/asap/staff/settings/library?orgId=${encodeURIComponent(requestedOrgId)}&_=${Date.now()}`, { cache: 'no-store' });",
  "    if (requestId !== libraryContextLoadSerial || requestedOrgId !== currentLibraryContextOrgId) {",
  "      return; // A newer request is in flight",
  "    }",
  "",
  "    settings = result;",
  "    isOverride = !!result.isOverride;",
  "    leapBibUrlPattern = settings.leapBibUrlPattern || '';",
  "",
  "    const resetBtn = document.getElementById('btn-reset-library-settings');",
  "    const statusAlert = document.getElementById('library-override-status');",
  "    const overrideMsg = document.getElementById('library-override-msg');",
  "",
  "    if (requestedOrgId === 'system') {",
  "      resetBtn.classList.add('hidden');",
  "      statusAlert.classList.add('hidden');",
  "      if (document.getElementById('system-staff-url-group')) {",
  "        document.getElementById('system-staff-url-group').classList.remove('hidden');",
  "      }",
  "      setFieldValue('system-staff-url', settings.staffUrl || '');",
  "      setFieldValue('leap-bib-url-pattern', leapBibUrlPattern);",
  "      if (document.getElementById('system-enabled-libraries-group')) {",
  "        document.getElementById('system-enabled-libraries-group').classList.remove('hidden');",
  "        renderLibraryParticipationCheckboxes();",
  "      }",
  "    } else {",
  "      statusAlert.classList.remove('hidden');",
  "      if (document.getElementById('system-staff-url-group')) {",
  "        document.getElementById('system-staff-url-group').classList.add('hidden');",
  "      }",
  "      if (document.getElementById('system-enabled-libraries-group')) {",
  "        document.getElementById('system-enabled-libraries-group').classList.add('hidden');",
  "      }",
  "      if (isOverride) {",
  "        statusAlert.className = 'alert alert-info mb-3 d-flex justify-content-between align-items-center';",
  "        overrideMsg.innerHTML = '<i class=\"fa fa-check-circle mr-1\"></i> Editing: <strong>' + escapeAttr(document.getElementById('library-context-display').textContent || 'selected library') + '</strong>. This library has custom settings.';",
  "        resetBtn.classList.remove('hidden');",
  "      } else {",
  "        statusAlert.className = 'alert alert-warning mb-3 d-flex justify-content-between align-items-center';",
  "        overrideMsg.innerHTML = '<i class=\"fa fa-info-circle mr-1\"></i> Editing: <strong>' + escapeAttr(document.getElementById('library-context-display').textContent || 'selected library') + '</strong>. This library is using system defaults. Saving will create a library-specific override.';",
  "        resetBtn.classList.add('hidden');",
  "      }",
  "    }",
  "",
  "    populateEmailTemplateForms(settings.emails || {});",
  "    populatePatronUiForms(settings.ui_text || {});",
  "    populateWorkflowForms(settings.workflow || {});",
  "    updateEmailStatusBanner(settings.emailStatus);",
  "    if (settings.organizationSync) {",
  "      const state = settings.organizationSync.status || 'not_loaded';",
  "      const message = settings.organizationSync.error || settings.organizationSync.message || organizationsStatusMessage;",
  "      setOrganizationsStatus(state, message);",
  "    }",
  "    return settings;",
  "",
  "  } catch (err) {",
  "    if (isPocketBaseAutoCancelError(err)) {",
  "      return;",
  "    }",
  "    console.error('Error loading library settings:', err);",
  "    showToast('Failed to load library settings', 'error');",
  "  }",
  "}",
  "",
  "populateWorkflowForms = function populateWorkflowForms(wf) {",
  "  setFieldValue('suggestion-limit', wf.suggestionLimit !== undefined ? wf.suggestionLimit : '5');",
  "  setFieldValue('suggestion-limit-msg', wf.suggestionLimitMessage || 'Weekly suggestion limit reached');",
  "  document.getElementById('outstanding-timeout-enabled').checked = !!wf.outstandingTimeoutEnabled;",
  "  setFieldValue('outstanding-timeout-days', wf.outstandingTimeoutDays !== undefined ? wf.outstandingTimeoutDays : '30');",
  "  ",
  "  setFieldChecked('outstanding-timeout-send-email', !!wf.outstandingTimeoutSendEmail);",
  "  workflowSettings.outstandingTimeoutSendEmail = !!wf.outstandingTimeoutSendEmail;",
  "  workflowSettings.outstandingTimeoutRejectionTemplateId = wf.outstandingTimeoutRejectionTemplateId || '';",
  "  ",
  "  document.getElementById('hold-pickup-timeout-enabled').checked = !!wf.holdPickupTimeoutEnabled;",
  "  setFieldValue('hold-pickup-timeout-days', wf.holdPickupTimeoutDays !== undefined ? wf.holdPickupTimeoutDays : '14');",
  "  document.getElementById('pending-hold-timeout-enabled').checked = !!wf.pendingHoldTimeoutEnabled;",
  "  setFieldValue('pending-hold-timeout-days', wf.pendingHoldTimeoutDays !== undefined ? wf.pendingHoldTimeoutDays : '14');",
  "",
  "  // Cache for checkbox renderer",
  "  lastWorkflowEnabledList = (wf.enabledLibraryOrgIds || '').split(',').map(s => s.trim()).filter(s => s.length > 0);",
  "",
  "  const container = document.getElementById('enabled-libraries-checkbox-container');",
  "  if (container) {",
  "    const checkboxes = container.querySelectorAll('input[type=\"checkbox\"]');",
  "    checkboxes.forEach(cb => {",
  "      cb.checked = lastWorkflowEnabledList.indexOf(cb.value) >= 0;",
  "    });",
  "  }",
  "",
  "  toggleTimeoutGroup();",
  "  updateAutoRejectEmailControls();",
  "  toggleHoldPickupTimeoutGroup();",
  "  togglePendingHoldTimeoutGroup();",
  "",
  "  setFieldValue('wf-common-authors-list', wf.commonAuthorsList || '');",
  "  setFieldValue('wf-common-authors-message', wf.commonAuthorsMessage || '');",
  "  document.getElementById('wf-common-authors-enabled').checked = !!wf.commonAuthorsEnabled;",
  "  toggleCommonAuthorsGroup();",
  "}",
  "",
  "populatePatronUiForms = function populatePatronUiForms(uiText) {",
  "  setFieldValue('ui-logo-alt', uiText.logoAlt || '');",
  "  setFieldValue('ui-patron-page-title', uiText.pageTitle || '');",
  "  setFieldValue('ui-barcode-label', uiText.barcodeLabel || '');",
  "  setFieldValue('ui-pin-label', uiText.pinLabel || '');",
  "  setFieldValue('ui-login-prompt', uiText.loginPrompt || 'Please enter your information below to start the suggestion process.');",
  "  setFieldValue('ui-login-note', uiText.loginNote || 'Use of this service requires a valid library card. Contact your library if you need assistance with your card or PIN.');",
  "  setFieldValue('ui-suggestion-note', uiText.suggestionFormNote || 'If the library decides to purchase your suggestion, we will automatically place a hold on it and send a confirmation email. Make sure to check your spam folder if you don\\'t see the email.');",
  "  setFieldValue('ui-no-email-msg', uiText.noEmailMessage || 'No email is specified on your library account, which means we won\\'t be able to send you updates regarding your suggestion. Please contact the library to add an email address to your account if you would like to receive status updates.');",
  "  setFieldValue('ui-success-title', uiText.successTitle || 'Suggestion Submitted');",
  "  setFieldValue('ui-success-msg', uiText.successMessage || 'You have successfully submitted your material suggestion! Check your email inbox for status updates.<div>Thank you for using our suggestion service.</div>');",
  "  setFieldValue('ui-already-submitted-msg', uiText.alreadySubmittedMessage || 'This suggestion has already been submitted from your account. Your previous request was submitted on {{duplicate_date}} and is currently {{duplicate_status}}.<div>Thank you for using this library\\'s suggestion service.</div>');",
  "  renderDuplicateStatusLabelSettings(uiText.duplicateStatusLabels || {}, uiText.duplicateStatusLabelsSource || '', !!uiText.duplicateStatusLabelsInherited);",
  "  setFieldValue('ui-ebook-msg', uiText.ebookMessage || '<p>This is an eBook suggestion, please use Libby to notify us of your interest.</p><p><a href=\"https://help.libbyapp.com/en-us/6260.htm\" target=\"_blank\" rel=\"noreferrer\">Learn how to suggest a purchase using Libby here.</a></p>');",
  "  setFieldValue('ui-eaudiobook-msg', uiText.eaudiobookMessage || '<p>This is an eAudiobook suggestion, please use Libby to notify us of your interest.</p><p><a href=\"https://help.libbyapp.com/en-us/6260.htm\" target=\"_blank\" rel=\"noreferrer\">Learn how to suggest a purchase using Libby here.</a></p>');",
  "",
  "  // Format Labels & Available Formats",
  "  const labels = uiText.formatLabels || {};",
  "  const available = uiText.availableFormats || ['book', 'audiobook_cd', 'dvd', 'music_cd', 'ebook', 'eaudiobook'];",
  "",
  "  // Merge into formatMap for the rest of the app",
  "  Object.keys(labels).forEach(k => formatMap[k] = labels[k]);",
  "  availableFormats = available;",
  "",
  "  renderFormatSettings();",
  "  updateModalFormatDropdowns();",
  "",
  "  renderOptionListEditor('ui-publication-options-editor', uiText.publicationOptions, defaultPublicationOptions);",
  "  renderOptionListEditor('ui-age-groups-editor', uiText.ageGroups, defaultAgeGroups);",
  "  const patronScope = document.getElementById('patron-options-scope');",
  "  if (patronScope) {",
  "    if (currentLibraryContextOrgId === 'system') {",
  "      patronScope.textContent = 'Editing global patron form defaults.';",
  "      patronScope.className = 'small mt-2 mb-0 text-muted';",
  "    } else if (uiText.patronSettingsInherited) {",
  "      patronScope.textContent = 'Showing inherited global patron form options. Saving will create custom options for the selected library only.';",
  "      patronScope.className = 'small mt-2 mb-0 text-warning';",
  "    } else {",
  "      patronScope.textContent = 'Editing custom patron form options for the selected library.';",
  "      patronScope.className = 'small mt-2 mb-0 text-info';",
  "    }",
  "  }",
  "  renderPatronFormatRulesEditor(uiText.formatRules);",
  "  setPublicationOptions(uiText.publicationOptions);",
  "  setAgeGroups(uiText.ageGroups);",
  "}",
  "",
  "normalizeDuplicateStatusLabels = function normalizeDuplicateStatusLabels(labels = {}) {",
  "  return { ...duplicateStatusLabelDefaults, ...(labels && typeof labels === 'object' ? labels : {}) };",
  "}",
  "",
  "renderDuplicateStatusLabelSettings = function renderDuplicateStatusLabelSettings(labels = {}, source = '', inherited = false) {",
  "  const container = document.getElementById('duplicate-status-labels-container');",
  "  if (!container) return;",
  "  const normalized = normalizeDuplicateStatusLabels(labels);",
  "  const scopeEl = document.getElementById('duplicate-status-labels-scope');",
  "  if (scopeEl) {",
  "    if (currentLibraryContextOrgId === 'system') {",
  "      scopeEl.textContent = 'Editing global default labels.';",
  "      scopeEl.className = 'small mb-3 text-muted';",
  "    } else if (inherited || source === 'global' || source === 'default') {",
  "      scopeEl.textContent = 'Showing inherited global labels. Saving will create labels for the selected library only.';",
  "      scopeEl.className = 'small mb-3 text-warning';",
  "    } else {",
  "      scopeEl.textContent = 'Editing custom labels for the selected library.';",
  "      scopeEl.className = 'small mb-3 text-info';",
  "    }",
  "  }",
  "  container.innerHTML = duplicateStatusLabelFields.map(([key, label]) => `",
  "    <div class=\"form-group col-md-6\">",
  "      <label for=\"duplicate-status-${escapeAttr(key)}\" class=\"small font-weight-bold\">${escapeAttr(label)}</label>",
  "      <input type=\"text\" id=\"duplicate-status-${escapeAttr(key)}\" class=\"form-control form-control-sm duplicate-status-label-input\" data-key=\"${escapeAttr(key)}\" value=\"${escapeAttr(normalized[key] || '')}\">",
  "    </div>",
  "  `).join('');",
  "}",
  "",
  "collectDuplicateStatusLabels = function collectDuplicateStatusLabels() {",
  "  const labels = {};",
  "  duplicateStatusLabelFields.forEach(([key]) => {",
  "    const el = document.getElementById(`duplicate-status-${key}`);",
  "    const value = el ? el.value.trim() : '';",
  "    labels[key] = value || duplicateStatusLabelDefaults[key] || '';",
  "  });",
  "  labels['Silently Closed'] = labels.silent || duplicateStatusLabelDefaults.silent;",
  "  return labels;",
  "}",
  "",
  "document.getElementById('btn-reset-library-settings').addEventListener('click', async () => {",
  "  if (currentLibraryContextOrgId === 'system') return;",
  "  const confirmed = await showConfirm('Reset library settings', 'Are you sure you want to delete this library\\'s overrides and revert to system defaults?');",
  "  if (confirmed) {",
  "    await authorizedJson('/api/asap/staff/settings/library', {",
  "      method: 'POST',",
  "      body: JSON.stringify({ orgId: currentLibraryContextOrgId, action: 'reset' })",
  "    });",
  "    showToast('Library settings reset to system defaults', 'success');",
  "    await loadLibrarySettings(currentLibraryContextOrgId);",
  "    markSettingsClean('clean');",
  "  }",
  "});",
  "",
  "loadStaffUsers = async function loadStaffUsers() {",
  "  const msgEl = document.getElementById('staff-users-msg');",
  "  const bodyEl = document.getElementById('staff-users-table-body');",
  "  const refreshBtn = document.getElementById('btn-refresh-staff-users');",
  "  if (!msgEl || !bodyEl) {",
  "    return;",
  "  }",
  "",
  "  if (refreshBtn) refreshBtn.disabled = true;",
  "  msgEl.textContent = 'Loading staff users...';",
  "  msgEl.className = 'mb-2 text-muted';",
  "  bodyEl.innerHTML = '<tr><td colspan=\"6\" class=\"text-muted\">Loading staff users...</td></tr>';",
  "",
  "  try {",
  "    const result = await authorizedJson('/api/asap/staff/users');",
  "    const users = Array.isArray(result.users) ? result.users : [];",
  "    canAssignSuperAdmin = !!result.canAssignSuperAdmin;",
  "    renderStaffUsers(users);",
  "    msgEl.textContent = users.length ? `Loaded ${users.length} staff user${users.length === 1 ? '' : 's'}.` : 'No staff users found.';",
  "    msgEl.className = 'mb-2 text-muted';",
  "  } catch (err) {",
  "    console.error('Failed to load staff users', err);",
  "    msgEl.textContent = err.message || 'Failed to load staff users.';",
  "    msgEl.className = 'mb-2 text-danger font-weight-bold';",
  "    bodyEl.innerHTML = '<tr><td colspan=\"6\" class=\"text-muted\">Unable to load staff users.</td></tr>';",
  "  } finally {",
  "    if (refreshBtn) refreshBtn.disabled = false;",
  "  }",
  "}",
  "",
  "renderStaffUsers = function renderStaffUsers(users) {",
  "  const bodyEl = document.getElementById('staff-users-table-body');",
  "  if (!bodyEl) {",
  "    return;",
  "  }",
  "",
  "  bodyEl.innerHTML = '';",
  "",
  "  if (!users.length) {",
  "    const tr = document.createElement('tr');",
  "    const td = document.createElement('td');",
  "    td.colSpan = 6;",
  "    td.className = 'text-muted';",
  "    td.textContent = 'No staff users found.';",
  "    tr.appendChild(td);",
  "    bodyEl.appendChild(tr);",
  "    return;",
  "  }",
  "",
  "",
  "  for (const user of users) {",
  "    const tr = document.createElement('tr');",
  "    tr.setAttribute('data-staff-id', user.id || '');",
  "",
  "    const tdUsername = document.createElement('td');",
  "    const strongUsername = document.createElement('strong');",
  "    strongUsername.textContent = user.username || '';",
  "    tdUsername.appendChild(strongUsername);",
  "    tr.appendChild(tdUsername);",
  "",
  "    const tdDomain = document.createElement('td');",
  "    if (user.domain) {",
  "      tdDomain.textContent = user.domain;",
  "    } else {",
  "      const span = document.createElement('span');",
  "      span.className = 'text-muted';",
  "      span.textContent = 'Default';",
  "      tdDomain.appendChild(span);",
  "    }",
  "    tr.appendChild(tdDomain);",
  "",
  "    const tdLibrary = document.createElement('td');",
  "    tdLibrary.textContent = user.libraryOrgName || user.libraryOrgId || (user.scope === 'system' ? 'System' : 'Unmapped');",
  "    tr.appendChild(tdLibrary);",
  "",
  "    const tdDisplayName = document.createElement('td');",
  "    if (user.displayName) {",
  "      tdDisplayName.textContent = user.displayName;",
  "    } else {",
  "      const span = document.createElement('span');",
  "      span.className = 'text-muted';",
  "      span.textContent = 'No display name';",
  "      tdDisplayName.appendChild(span);",
  "    }",
  "    tr.appendChild(tdDisplayName);",
  "",
  "    const tdRole = document.createElement('td');",
  "    const select = document.createElement('select');",
  "    select.className = 'form-control form-control-sm staff-role-select';",
  "",
  "    const role = ['staff', 'admin', 'super_admin'].includes(String(user.role || '').toLowerCase()) ? String(user.role || '').toLowerCase() : 'staff';",
  "",
  "    select.appendChild(new Option('Staff', 'staff', false, role === 'staff'));",
  "    select.appendChild(new Option('Admin', 'admin', false, role === 'admin'));",
  "",
  "    if (canAssignSuperAdmin) {",
  "      select.appendChild(new Option('Super Admin', 'super_admin', false, role === 'super_admin'));",
  "    }",
  "",
  "    tdRole.appendChild(select);",
  "    tr.appendChild(tdRole);",
  "",
  "    const tdSave = document.createElement('td');",
  "    const btn = document.createElement('button');",
  "    btn.type = 'button';",
  "    btn.className = 'btn btn-sm btn-primary staff-role-save mr-1';",
  "    btn.textContent = 'Save Role';",
  "    tdSave.appendChild(btn);",
  "    const del = document.createElement('button');",
  "    del.type = 'button';",
  "    del.className = 'btn btn-sm btn-outline-danger staff-user-delete';",
  "    del.textContent = 'Remove';",
  "    tdSave.appendChild(del);",
  "    tr.appendChild(tdSave);",
  "",
  "    bodyEl.appendChild(tr);",
  "  }",
  "}",
  "",
  "const staffUsersTableBody = document.getElementById('staff-users-table-body');",
  "if (staffUsersTableBody) {",
  "  staffUsersTableBody.addEventListener('click', async (e) => {",
  "    const row = e.target.closest('tr[data-staff-id]');",
  "    if (!row) return;",
  "    const delBtn = e.target.closest('.staff-user-delete');",
  "    if (delBtn) {",
  "      const id = row.getAttribute('data-staff-id');",
  "      const ok = await showConfirm('Remove staff member', 'Are you sure you want to remove this staff user from access?');",
  "      if (!ok) return;",
  "      delBtn.disabled = true;",
  "      try {",
  "        await authorizedJson(`/api/asap/staff/users/${encodeURIComponent(id)}`, { method: 'DELETE' });",
  "        await populateStaffLibraryOptions();",
  "    await loadStaffUsers();",
  "      } catch (err) {",
  "        const msgEl = document.getElementById('staff-users-msg');",
  "        if (msgEl) { msgEl.textContent = err.message || 'Failed to remove staff user.'; msgEl.className = 'mb-2 text-danger font-weight-bold'; }",
  "      } finally { delBtn.disabled = false; }",
  "      return;",
  "    }",
  "",
  "    const btn = e.target.closest('.staff-role-save');",
  "    if (!btn) return;",
  "",
  "",
  "    if (!row) return;",
  "",
  "    const id = row.getAttribute('data-staff-id');",
  "    const select = row.querySelector('.staff-role-select');",
  "    const nextRole = select ? select.value : 'staff';",
  "    const msgEl = document.getElementById('staff-users-msg');",
  "",
  "    btn.disabled = true;",
  "    if (msgEl) {",
  "      msgEl.textContent = 'Saving role...';",
  "      msgEl.className = 'mb-2 text-muted';",
  "    }",
  "",
  "    try {",
  "      await authorizedJson(`/api/asap/staff/users/${encodeURIComponent(id)}/role`, {",
  "        method: 'POST',",
  "        body: JSON.stringify({ role: nextRole })",
  "      });",
  "      if (msgEl) {",
  "        msgEl.textContent = 'Staff role updated successfully.';",
  "        msgEl.className = 'mb-2 text-success font-weight-bold';",
  "      }",
  "      await populateStaffLibraryOptions();",
  "    await loadStaffUsers();",
  "    } catch (err) {",
  "      console.error('Failed to update staff role', err);",
  "      if (msgEl) {",
  "        msgEl.textContent = err.message || 'Failed to update staff role.';",
  "        msgEl.className = 'mb-2 text-danger font-weight-bold';",
  "      }",
  "    } finally {",
  "      btn.disabled = false;",
  "    }",
  "  });",
  "}",
  "",
  "const refreshStaffUsersBtn = document.getElementById('btn-refresh-staff-users');",
  "if (refreshStaffUsersBtn) {",
  "  refreshStaffUsersBtn.addEventListener('click', (e) => {",
  "    e.preventDefault();",
  "    loadStaffUsers();",
  "  });",
  "}",
  "",
  "populateStaffLibraryOptions = async function populateStaffLibraryOptions() {",
  "  const select = document.getElementById('staff-add-library');",
  "  if (!select) return;",
  "  select.innerHTML = '<option value=\"\">Select library</option>';",
  "  const me = pb.authStore.model || {};",
  "  if (isSuperAdminStaff()) {",
  "    const orgs = await pb.collection('polaris_organizations').getFullList({",
  "      filter: 'organizationCodeId = \"2\"',",
  "      sort: 'displayName',",
  "      requestKey: 'polaris-orgs-staff-options'",
  "    });",
  "    orgs.forEach(org => select.appendChild(new Option(`${org.displayName || org.name} (ID ${org.organizationId})`, org.organizationId)));",
  "  } else if (me.libraryOrgId) {",
  "    select.appendChild(new Option(`${me.libraryOrgName || me.libraryOrgId} (ID ${me.libraryOrgId})`, me.libraryOrgId));",
  "    select.value = me.libraryOrgId;",
  "  }",
  "}",
  "",
  "const addStaffBtn = document.getElementById('btn-add-staff-user');",
  "if (addStaffBtn) {",
  "  addStaffBtn.addEventListener('click', async () => {",
  "    const identity = getFieldValue('staff-add-identity').trim();",
  "    const libraryOrgId = getFieldValue('staff-add-library').trim();",
  "    const role = getFieldValue('staff-add-role').trim() || 'staff';",
  "    const msgEl = document.getElementById('staff-users-msg');",
  "    if (!identity) return showAlert('Enter a staff username or identity.');",
  "    if (role !== 'super_admin' && !libraryOrgId) return showAlert('Select a library for this staff member.');",
  "    try {",
  "      const libSelect = document.getElementById('staff-add-library');",
  "      const opt = libSelect && libSelect.selectedIndex >= 0 ? libSelect.options[libSelect.selectedIndex] : null;",
  "      await authorizedJson('/api/asap/staff/users', { method: 'POST', body: JSON.stringify({ username: identity, libraryOrgId, libraryOrgName: opt ? opt.text : '', role }) });",
  "      setFieldValue('staff-add-identity', '');",
  "      if (msgEl) { msgEl.textContent = 'Staff member added.'; msgEl.className = 'mb-2 text-success font-weight-bold'; }",
  "      await populateStaffLibraryOptions();",
  "    await loadStaffUsers();",
  "    } catch (err) {",
  "      if (msgEl) { msgEl.textContent = err.message || 'Failed to add staff member.'; msgEl.className = 'mb-2 text-danger font-weight-bold'; }",
  "    }",
  "  });",
  "}",
  "",
  "buildSettingsPayload = function buildSettingsPayload() {",
  "  function positiveInt(id, fallback, label) {",
  "    const raw = getFieldValue(id, String(fallback)).trim();",
  "    if (!raw) return fallback;",
  "    const value = parseInt(raw, 10);",
  "    if (!Number.isFinite(value) || value < 1) {",
  "      throw new Error(`${label} must be a number greater than 0.`);",
  "    }",
  "    return value;",
  "  }",
  "",
  "  let staffUrl = '';",
  "  let nextLeapBibUrlPattern = leapBibUrlPattern || '';",
  "  if (isSuperAdminStaff() && currentLibraryContextOrgId === 'system') {",
  "    staffUrl = getFieldValue('system-staff-url').trim();",
  "    const staffUrlError = validateStaffUrl(staffUrl);",
  "    if (staffUrlError) {",
  "      throw new Error(staffUrlError);",
  "    }",
  "    staffUrl = normalizeStaffUrl(staffUrl);",
  "    setFieldValue('system-staff-url', staffUrl);",
  "    nextLeapBibUrlPattern = normalizeLeapBibUrlPattern(getFieldValue('leap-bib-url-pattern').trim());",
  "    setFieldValue('leap-bib-url-pattern', nextLeapBibUrlPattern);",
  "  }",
  "",
  "  const smtp = {",
  "    host: getFieldValue('smtp-host').trim(),",
  "    port: positiveInt('smtp-port', 587, 'SMTP port'),",
  "    username: getFieldValue('smtp-username').trim(),",
  "    password: getFieldValue('smtp-password'),",
  "    tls: getFieldChecked('smtp-tls', true)",
  "  };",
  "",
  "  const polaris = collectSettingsPolaris();",
  "",
  "  const uiText = {",
  "    logoAlt: getFieldValue('ui-logo-alt'),",
  "    pageTitle: getFieldValue('ui-patron-page-title'),",
  "    barcodeLabel: getFieldValue('ui-barcode-label'),",
  "    pinLabel: getFieldValue('ui-pin-label'),",
  "    loginPrompt: getFieldValue('ui-login-prompt'),",
  "    loginNote: getFieldValue('ui-login-note'),",
  "    suggestionFormNote: getFieldValue('ui-suggestion-note'),",
  "    noEmailMessage: getFieldValue('ui-no-email-msg'),",
  "    successTitle: getFieldValue('ui-success-title'),",
  "    successMessage: getFieldValue('ui-success-msg'),",
  "    alreadySubmittedMessage: getFieldValue('ui-already-submitted-msg'),",
  "    duplicateStatusLabels: collectDuplicateStatusLabels(),",
  "    ebookMessage: getFieldValue('ui-ebook-msg'),",
  "    eaudiobookMessage: getFieldValue('ui-eaudiobook-msg'),",
  "    formatLabels: collectFormatLabels(),",
  "    availableFormats: collectAvailableFormats(),",
  "    publicationOptions: collectOptionList('ui-publication-options-editor', defaultPublicationOptions),",
  "    ageGroups: collectOptionList('ui-age-groups-editor', defaultAgeGroups),",
  "    formatRules: collectPatronFormatRules()",
  "  };",
  "",
  "  const emails = {",
  "    fromAddress: getFieldValue('email-from-address'),",
  "    fromName: getFieldValue('email-from-name'),",
  "    suggestion_submitted: {",
  "      subject: getFieldValue('email-submit-subject'),",
  "      body: getFieldValue('email-submit-body')",
  "    },",
  "    already_owned: {",
  "      subject: getFieldValue('email-owned-subject'),",
  "      body: getFieldValue('email-owned-body')",
  "    },",
  "    rejected: {",
  "      subject: getFieldValue('email-rejected-subject'),",
  "      body: getFieldValue('email-rejected-body')",
  "    },",
  "    rejection_templates: currentRejectionTemplates,",
  "    hold_placed: {",
  "      subject: getFieldValue('email-hold-subject'),",
  "      body: getFieldValue('email-hold-body')",
  "    }",
  "  };",
  "",
  "  const sendAutoRejectEmail = getFieldChecked('outstanding-timeout-send-email');",
  "  const selectedTemplateId = getFieldValue('outstanding-timeout-rejection-template-id');",
  "  if (getFieldChecked('outstanding-timeout-enabled') && sendAutoRejectEmail) {",
  "    if (!currentRejectionTemplates.length) {",
  "      throw new Error('Create at least one rejection template before enabling auto-reject email.');",
  "    }",
  "    if (currentRejectionTemplates.length > 1 && !selectedTemplateId) {",
  "      throw new Error('Select a rejection template for auto-reject emails.');",
  "    }",
  "  }",
  "",
  "  const payload = {",
  "    smtp, polaris, ui_text: uiText, emails,",
  "    suggestionLimit: positiveInt('suggestion-limit', 5, 'Suggestion limit'),",
  "    suggestionLimitMessage: getFieldValue('suggestion-limit-msg'),",
  "    outstandingTimeoutEnabled: getFieldChecked('outstanding-timeout-enabled'),",
  "    outstandingTimeoutDays: positiveInt('outstanding-timeout-days', 30, 'Auto-reject stalled suggestions days'),",
  "    outstandingTimeoutSendEmail: sendAutoRejectEmail,",
  "    outstandingTimeoutRejectionTemplateId: currentRejectionTemplates.length === 1 ? currentRejectionTemplates[0].id : selectedTemplateId,",
  "    holdPickupTimeoutEnabled: getFieldChecked('hold-pickup-timeout-enabled'),",
  "    holdPickupTimeoutDays: positiveInt('hold-pickup-timeout-days', 14, 'Auto-close unpicked-up holds days'),",
  "    pendingHoldTimeoutEnabled: getFieldChecked('pending-hold-timeout-enabled'),",
  "    pendingHoldTimeoutDays: positiveInt('pending-hold-timeout-days', 14, 'Auto-close pending holds days'),",
  "    enabledLibraryOrgIds: collectEnabledLibraryIds(),",
  "    commonAuthorsEnabled: getFieldChecked('wf-common-authors-enabled'),",
  "    commonAuthorsList: sortAuthorsByLastName(getFieldValue('wf-common-authors-list')),",
  "    commonAuthorsMessage: getFieldValue('wf-common-authors-message')",
  "  };",
  "",
  "  if (isSuperAdminStaff() && currentLibraryContextOrgId === 'system') {",
  "    payload.staffUrl = staffUrl;",
  "    payload.leapBibUrlPattern = nextLeapBibUrlPattern;",
  "  }",
  "",
  "  const fileInput = document.getElementById('ui-logo-file');",
  "  if (fileInput && fileInput.files.length > 0) {",
  "    payload.logo = fileInput.files[0];",
  "  }",
  "",
  "  return payload;",
  "}",
  "",
  "saveSettings = async function saveSettings(options = {}) {",
  "  const submitBtn = settingsForm.querySelector('button[type=\"submit\"]');",
  "  const triggerBtn = options.button || null;",
  "  const buttons = Array.from(new Set([submitBtn, triggerBtn].filter(Boolean)));",
  "  const msg = document.getElementById('settings-msg');",
  "  let saveHadError = false;",
  "  let saveSucceeded = false;",
  "",
  "  settingsSaving = true;",
  "  updateSaveBarState('saving');",
  "  buttons.forEach(button => {",
  "    button.disabled = true;",
  "  });",
  "  msg.textContent = options.pendingText || 'Saving...';",
  "  msg.className = 'mt-2 font-weight-bold text-info';",
  "",
  "  try {",
  "    if (!validateSmtpHostField(true)) {",
  "      throw new Error('SMTP host is invalid.');",
  "    }",
  "    const isSuper = isSuperAdminStaff();",
  "    const payload = buildSettingsPayload();",
  "",
  "    // Save templates via the new library-scoped API",
  "    const libraryPayload = {",
  "      orgId: currentLibraryContextOrgId,",
  "      staffUrl: payload.staffUrl,",
  "      leapBibUrlPattern: payload.leapBibUrlPattern,",
  "      smtp: payload.smtp,",
  "      polaris: payload.polaris,",
  "      emails: payload.emails,",
  "      ui_text: payload.ui_text,",
  "      workflow: {",
  "        suggestionLimit: payload.suggestionLimit,",
  "        suggestionLimitMessage: payload.suggestionLimitMessage,",
  "        outstandingTimeoutEnabled: payload.outstandingTimeoutEnabled,",
  "        outstandingTimeoutDays: payload.outstandingTimeoutDays,",
  "        outstandingTimeoutSendEmail: payload.outstandingTimeoutSendEmail,",
  "        outstandingTimeoutRejectionTemplateId: payload.outstandingTimeoutRejectionTemplateId,",
  "        holdPickupTimeoutEnabled: payload.holdPickupTimeoutEnabled,",
  "        holdPickupTimeoutDays: payload.holdPickupTimeoutDays,",
  "        pendingHoldTimeoutEnabled: payload.pendingHoldTimeoutEnabled,",
  "        pendingHoldTimeoutDays: payload.pendingHoldTimeoutDays,",
  "        enabledLibraryOrgIds: payload.enabledLibraryOrgIds,",
  "        commonAuthorsEnabled: payload.commonAuthorsEnabled,",
  "        commonAuthorsList: payload.commonAuthorsList,",
  "        commonAuthorsMessage: payload.commonAuthorsMessage",
  "      }",
  "    };",
  "",
  "    const libraryPromise = authorizedJson('/api/asap/staff/settings/library', {",
  "      method: 'POST',",
  "      body: JSON.stringify(libraryPayload)",
  "    });",
  "",
  "    await libraryPromise;",
  "    msg.textContent = options.successText || 'Settings saved.';",
  "    msg.className = 'mt-2 font-weight-bold text-success';",
  "    if (options.clearDelay !== 0) {",
  "      setTimeout(() => msg.textContent = '', options.clearDelay || 3000);",
  "    }",
  "    await loadSettings({ showErrors: false }); // Sync internal state (also triggers loadLibrarySettings)",
  "    await loadStaffConfig(); // Refresh logo and titles immediately after saving",
  "    loadStaffUsers();",
  "    saveSucceeded = true;",
  "    showToast('Settings saved.', 'success');",
  "    return true;",
  "  } catch (err) {",
  "    saveHadError = true;",
  "    console.error(err);",
  "    msg.textContent = err.message || 'Failed to save settings.';",
  "    msg.className = 'mb-3 font-weight-bold text-danger';",
  "    updateSaveBarState('error');",
  "    return false;",
  "  } finally {",
  "    settingsSaving = false;",
  "    buttons.forEach(button => {",
  "      button.disabled = false;",
  "    });",
  "    updateSaveBarState(saveHadError ? 'error' : (saveSucceeded ? 'saved' : (settingsDirty ? 'dirty' : 'clean')));",
  "  }",
  "}",
  "",
  "settingsForm.addEventListener('submit', async (e) => {",
  "  e.preventDefault();",
  "  await saveSettings();",
  "});",
  "settingsForm.addEventListener('input', markSettingsDirty);",
  "settingsForm.addEventListener('change', markSettingsDirty);",
  "document.getElementById('ui-publication-options-editor')?.addEventListener('click', handleOptionListClick);",
  "document.getElementById('ui-age-groups-editor')?.addEventListener('click', handleOptionListClick);",
  "document.getElementById('btn-add-publication-option')?.addEventListener('click', () => addOptionListRow('ui-publication-options-editor', defaultPublicationOptions));",
  "document.getElementById('btn-add-age-group')?.addEventListener('click', () => addOptionListRow('ui-age-groups-editor', defaultAgeGroups));",
  "",
  "loadStaffConfig = async function loadStaffConfig() {",
  "  try {",
  "    const res = await fetch('/api/asap/config');",
  "    const config = await res.json();",
  "    if (config) {",
  "      if (config.logoUrl) {",
  "        document.getElementById('app-icon').href = config.logoUrl;",
  "        document.getElementById('setup-logo').src = config.logoUrl;",
  "        document.getElementById('login-logo').src = config.logoUrl;",
  "        document.getElementById('nav-logo').src = config.logoUrl;",
  "      }",
  "      if (config.logoAlt) {",
  "        document.getElementById('setup-logo').alt = config.logoAlt;",
  "        document.getElementById('login-logo').alt = config.logoAlt;",
  "        document.getElementById('nav-logo').alt = config.logoAlt;",
  "      }",
  "      setPublicationOptions(config.publicationOptions);",
  "    }",
  "  } catch (err) {",
  "    console.error('Failed to load global config');",
  "  }",
  "}",
  "",
  "initStaffApp = async function initStaffApp() {",
  "  closeOpenDialogs();",
  "  closeActionMenu?.();",
  "  initSettingsNavigation();",
  "  await loadStaffConfig();",
  "  await loadSetupStatus();",
  "  checkAuth();",
  "}",
  "",
  "",
  "document.getElementById('outstanding-timeout-enabled').addEventListener('change', () => {",
  "  toggleTimeoutGroup();",
  "  updateAutoRejectEmailControls();",
  "});",
  "document.getElementById('outstanding-timeout-send-email').addEventListener('change', updateAutoRejectEmailControls);",
  "",
  "toggleTimeoutGroup = function toggleTimeoutGroup() {",
  "  const group = document.getElementById('timeout-config-group');",
  "  const enabled = document.getElementById('outstanding-timeout-enabled').checked;",
  "  if (enabled) {",
  "    group.classList.remove('hidden');",
  "  } else {",
  "    group.classList.add('hidden');",
  "  }",
  "}",
  "",
  "toggleHoldPickupTimeoutGroup = function toggleHoldPickupTimeoutGroup() {",
  "  const group = document.getElementById('hold-pickup-timeout-group');",
  "  const enabled = document.getElementById('hold-pickup-timeout-enabled').checked;",
  "  if (enabled) {",
  "    group.classList.remove('hidden');",
  "  } else {",
  "    group.classList.add('hidden');",
  "  }",
  "}",
  "",
  "togglePendingHoldTimeoutGroup = function togglePendingHoldTimeoutGroup() {",
  "  const group = document.getElementById('pending-hold-timeout-group');",
  "  const enabled = document.getElementById('pending-hold-timeout-enabled').checked;",
  "  if (enabled) {",
  "    group.classList.remove('hidden');",
  "  } else {",
  "    group.classList.add('hidden');",
  "  }",
  "}",
  "",
  "toggleCommonAuthorsGroup = function toggleCommonAuthorsGroup() {",
  "  const group = document.getElementById('common-authors-config-group');",
  "  const enabled = document.getElementById('wf-common-authors-enabled').checked;",
  "  if (enabled) {",
  "    group.classList.remove('hidden');",
  "  } else {",
  "    group.classList.add('hidden');",
  "  }",
  "}",
  "",
  "sortAuthorsByLastName = function sortAuthorsByLastName(authorsListStr) {",
  "  if (!authorsListStr) return '';",
  "  const authors = authorsListStr.split('\\n').map(s => s.trim()).filter(s => s.length > 0);",
  "  authors.sort((a, b) => {",
  "    // Basic last name detection (everything after the first comma, or the last word)",
  "    const getLastName = (name) => {",
  "      if (name.includes(',')) return name.split(',')[0].trim();",
  "      const parts = name.split(' ');",
  "      return parts[parts.length - 1].trim();",
  "    };",
  "    const lastA = getLastName(a).toLowerCase();",
  "    const lastB = getLastName(b).toLowerCase();",
  "    return lastA.localeCompare(lastB);",
  "  });",
  "  return authors.join('\\n');",
  "}",
  "",
  "document.getElementById('hold-pickup-timeout-enabled').addEventListener('change', toggleHoldPickupTimeoutGroup);",
  "document.getElementById('pending-hold-timeout-enabled').addEventListener('change', togglePendingHoldTimeoutGroup);",
  "document.getElementById('wf-common-authors-enabled').addEventListener('change', toggleCommonAuthorsGroup);",
  "",
  "document.getElementById('edit-bibid').addEventListener('keydown', (e) => {",
  "  if (e.key === 'Enter') {",
  "    e.preventDefault();",
  "    document.getElementById('btn-bib-lookup').click();",
  "  }",
  "});",
  "",
  "document.getElementById('edit-bibid').addEventListener('input', () => {",
  "  const bibId = document.getElementById('edit-bibid').value.trim();",
  "  renderEditLeapBibLink(bibId);",
  "  if (verifiedBibId && bibId !== verifiedBibId) {",
  "    verifiedBibId = '';",
  "    document.getElementById('bib-info-display').classList.add('hidden');",
  "    document.getElementById('bib-info-text').textContent = '';",
  "  }",
  "});",
  "",
  "renderFormatSettings = function renderFormatSettings() {",
  "  const container = document.getElementById('format-settings-container');",
  "  if (!container) return;",
  "",
  "  // Show enabled formats first (in their saved order), then disabled ones",
  "  const enabledKeys = availableFormats.filter(k => formatMap[k] !== undefined);",
  "  const disabledKeys = Object.keys(formatMap).filter(k => !availableFormats.includes(k));",
  "  const allKeys = [...enabledKeys, ...disabledKeys];",
  "",
  "  container.innerHTML = `",
  "    <div class=\"table-responsive\">",
  "      <table class=\"table table-sm mb-0\">",
  "        <thead>",
  "          <tr>",
  "            <th class=\"format-drag-col\"></th>",
  "            <th class=\"format-show-col\">Show</th>",
  "            <th class=\"format-key-col\">Format key</th>",
  "            <th>Display label</th>",
  "            <th class=\"format-remove-col\"></th>",
  "          </tr>",
  "        </thead>",
  "        <tbody id=\"format-settings-body\">",
  "          ${allKeys.map(key => `",
  "            <tr class=\"format-setting-row\" data-key=\"${escapeAttr(key)}\" draggable=\"true\">",
  "              <td class=\"align-middle text-muted format-drag-handle\">&#8597;</td>",
  "              <td class=\"align-middle\">",
  "                <div class=\"custom-control custom-checkbox\">",
  "                  <input type=\"checkbox\" class=\"custom-control-input format-enabled-check\" id=\"fmt-chk-${key}\" ${availableFormats.includes(key) ? 'checked' : ''}>",
  "                  <label class=\"custom-control-label\" for=\"fmt-chk-${key}\"></label>",
  "                </div>",
  "              </td>",
  "              <td class=\"align-middle\"><code>${escapeAttr(key)}</code></td>",
  "              <td>",
  "                <input type=\"text\" class=\"form-control form-control-sm format-label-input\" value=\"${escapeAttr(formatMap[key] || key)}\">",
  "              </td>",
  "              <td class=\"text-right align-middle\">",
  "                ${['book', 'audiobook_cd', 'dvd', 'music_cd', 'ebook', 'eaudiobook'].includes(key) ? '' : '<button type=\"button\" class=\"btn btn-sm btn-link text-danger p-0 btn-remove-format\">&times;</button>'}",
  "              </td>",
  "            </tr>",
  "          `).join('')}",
  "        </tbody>",
  "      </table>",
  "    </div>",
  "  `;",
  "",
  "  initFormatDragSort();",
  "}",
  "",
  "initFormatDragSort = function initFormatDragSort() {",
  "  const tbody = document.getElementById('format-settings-body');",
  "  if (!tbody) return;",
  "",
  "  let draggingRow = null;",
  "",
  "  tbody.addEventListener('dragstart', (e) => {",
  "    draggingRow = e.target.closest('tr');",
  "    if (draggingRow) {",
  "      draggingRow.classList.add('format-row-dragging');",
  "      e.dataTransfer.effectAllowed = 'move';",
  "    }",
  "  });",
  "",
  "  tbody.addEventListener('dragend', () => {",
  "    if (draggingRow) {",
  "      draggingRow.classList.remove('format-row-dragging');",
  "      draggingRow = null;",
  "    }",
  "    // Remove all drag-over highlights",
  "    tbody.querySelectorAll('tr').forEach(r => r.classList.remove('format-row-drop-target'));",
  "  });",
  "",
  "  tbody.addEventListener('dragover', (e) => {",
  "    e.preventDefault();",
  "    e.dataTransfer.dropEffect = 'move';",
  "    const target = e.target.closest('tr');",
  "    if (target && target !== draggingRow) {",
  "      tbody.querySelectorAll('tr').forEach(r => r.classList.remove('format-row-drop-target'));",
  "      target.classList.add('format-row-drop-target');",
  "    }",
  "  });",
  "",
  "  tbody.addEventListener('drop', (e) => {",
  "    e.preventDefault();",
  "    const target = e.target.closest('tr');",
  "    tbody.querySelectorAll('tr').forEach(r => r.classList.remove('format-row-drop-target'));",
  "    if (target && draggingRow && target !== draggingRow) {",
  "      tbody.insertBefore(draggingRow, target);",
  "      markSettingsDirty();",
  "    }",
  "  });",
  "}",
  "",
  "collectFormatLabels = function collectFormatLabels() {",
  "  const labels = {};",
  "  document.querySelectorAll('.format-setting-row').forEach(row => {",
  "    const key = row.getAttribute('data-key');",
  "    const label = row.querySelector('.format-label-input').value.trim();",
  "    if (key && label) labels[key] = label;",
  "  });",
  "  return labels;",
  "}",
  "",
  "collectAvailableFormats = function collectAvailableFormats() {",
  "  const available = [];",
  "  document.querySelectorAll('.format-setting-row').forEach(row => {",
  "    const key = row.getAttribute('data-key');",
  "    const enabled = row.querySelector('.format-enabled-check').checked;",
  "    if (key && enabled) available.push(key);",
  "  });",
  "  return available;",
  "}",
  "",
  "updateModalFormatDropdowns = function updateModalFormatDropdowns() {",
  "  ['edit-format', 'new-format'].forEach(id => {",
  "    const select = document.getElementById(id);",
  "    if (!select) return;",
  "",
  "    // Keep current value",
  "    const val = select.value;",
  "",
  "    // Only include availableFormats",
  "    select.innerHTML = availableFormats.map(k => `",
  "      <option value=\"${escapeAttr(k)}\">${escapeAttr(formatMap[k] || k)}</option>",
  "    `).join('');",
  "",
  "    // Try to restore value, or fallback to first",
  "    select.value = availableFormats.includes(val) ? val : (availableFormats[0] || '');",
  "  });",
  "}",
  "",
  "const btnAddFormat = document.getElementById('btn-add-format');",
  "if (btnAddFormat) {",
  "  btnAddFormat.addEventListener('click', () => {",
  "    const keyInput = document.getElementById('new-format-key');",
  "    const labelInput = document.getElementById('new-format-label');",
  "    const rawKey = keyInput ? keyInput.value.trim() : '';",
  "    const rawLabel = labelInput ? labelInput.value.trim() : '';",
  "    const key = rawKey.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');",
  "    if (!key) {",
  "      setInlineStatus('new-format-error', 'Enter a short format key, such as videogame.', 'danger');",
  "      if (keyInput) keyInput.focus();",
  "      return;",
  "    }",
  "    if (!/^[a-z0-9_]+$/.test(key)) {",
  "      setInlineStatus('new-format-error', 'Use only letters, numbers, and underscores for the format key.', 'danger');",
  "      if (keyInput) keyInput.focus();",
  "      return;",
  "    }",
  "    if (formatMap[key]) {",
  "      setInlineStatus('new-format-error', 'This format key already exists.', 'danger');",
  "      if (keyInput) keyInput.focus();",
  "      return;",
  "    }",
  "    const label = rawLabel || key.replace(/_/g, ' ').replace(/\\b\\w/g, c => c.toUpperCase());",
  "    formatMap[key] = label;",
  "    availableFormats.push(key);",
  "    if (keyInput) keyInput.value = '';",
  "    if (labelInput) labelInput.value = '';",
  "    setInlineStatus('new-format-error', `Added ${label}. Save settings to keep this format.`, 'success');",
  "    renderFormatSettings();",
  "    renderPatronFormatRulesEditor(collectPatronFormatRules());",
  "    markSettingsDirty();",
  "  });",
  "}",
  "",
  "const formatSettingsContainer = document.getElementById('format-settings-container');",
  "if (formatSettingsContainer) {",
  "  formatSettingsContainer.addEventListener('click', async (e) => {",
  "    if (e.target.classList.contains('btn-remove-format')) {",
  "      const row = e.target.closest('tr');",
  "      const key = row.getAttribute('data-key');",
  "      if (await showConfirm('Remove format', `Remove format \"${key}\"? This will only remove it from the settings list. Existing suggestions with this format will remain in the database.`)) {",
  "        delete formatMap[key];",
  "        availableFormats = availableFormats.filter(k => k !== key);",
  "        renderFormatSettings();",
  "        renderPatronFormatRulesEditor(collectPatronFormatRules());",
  "      }",
  "    }",
  "  });",
  "}",
  "",
  "// Keep duplicate sender fields in sync between Email Settings and SMTP Settings",
  "syncInputPair = function syncInputPair(idA, idB) {",
  "  const elA = document.getElementById(idA);",
  "  const elB = document.getElementById(idB);",
  "  if (elA && elB) {",
  "    elA.addEventListener('input', (e) => elB.value = e.target.value);",
  "    elB.addEventListener('input', (e) => elA.value = e.target.value);",
  "  }",
  "}",
  "syncInputPair('email-from-address', 'smtp-from');",
  "syncInputPair('email-from-name', 'smtp-from-name');",
  "const smtpHostInput = document.getElementById('smtp-host');",
  "if (smtpHostInput) {",
  "  smtpHostInput.addEventListener('blur', () => validateSmtpHostField(true));",
  "  smtpHostInput.addEventListener('input', () => {",
  "    if (isValidSmtpHost(smtpHostInput.value) || !smtpHostInput.value.trim()) {",
  "      const resultEl = document.getElementById('smtp-test-result');",
  "      if (resultEl && resultEl.className.includes('text-danger') && resultEl.textContent.includes('SMTP host')) {",
  "        resultEl.textContent = '';",
  "        resultEl.className = 'd-block mt-2';",
  "      }",
  "    }",
  "  });",
  "}",
  "",
  "renderRejectionTemplates = function renderRejectionTemplates() {",
  "  const container = document.getElementById('rejection-templates-container');",
  "  if (!container) return;",
  "",
  "  if (currentRejectionTemplates.length === 0) {",
  "    container.innerHTML = '<div class=\"text-muted small\">No additional rejection templates configured.</div>';",
  "    return;",
  "  }",
  "",
  "  container.innerHTML = '';",
  "  currentRejectionTemplates.forEach((template, index) => {",
  "    const wrapper = document.createElement('div');",
  "    wrapper.className = 'border rounded p-3 mb-3 bg-light position-relative';",
  "",
  "    wrapper.innerHTML = `",
  "      <button type=\"button\" class=\"btn btn-sm btn-outline-danger position-absolute rejection-template-remove\" onclick=\"removeRejectionTemplate(${index})\" title=\"Remove template\">&times;</button>",
  "      <div class=\"form-group\">",
  "        <label>Template name</label>",
  "        <input type=\"text\" class=\"form-control form-control-sm\" value=\"${escapeAttr(template.name || '')}\" onchange=\"updateRejectionTemplate(${index}, 'name', this.value)\">",
  "      </div>",
  "      <div class=\"form-group\">",
  "        <label>Subject</label>",
  "        <input type=\"text\" class=\"form-control form-control-sm\" value=\"${escapeAttr(template.subject || '')}\" onchange=\"updateRejectionTemplate(${index}, 'subject', this.value)\">",
  "      </div>",
  "      <div class=\"form-group mb-0\">",
  "        <label>Body</label>",
  "        <textarea class=\"form-control form-control-sm\" rows=\"3\" onchange=\"updateRejectionTemplate(${index}, 'body', this.value)\">${escapeAttr(template.body || '')}</textarea>",
  "      </div>",
  "    `;",
  "    container.appendChild(wrapper);",
  "  });",
  "}",
  "",
  "updateRejectionTemplate = function updateRejectionTemplate(index, field, value) {",
  "  if (currentRejectionTemplates[index]) {",
  "    currentRejectionTemplates[index][field] = value;",
  "    markSettingsDirty();",
  "  }",
  "}",
  "",
  "removeRejectionTemplate = function removeRejectionTemplate(index) {",
  "  currentRejectionTemplates.splice(index, 1);",
  "  renderRejectionTemplates();",
  "  markSettingsDirty();",
  "}",
  "",
  "const btnAddRejectionTemplate = document.getElementById('btn-add-rejection-template');",
  "if (btnAddRejectionTemplate) {",
  "  btnAddRejectionTemplate.addEventListener('click', () => {",
  "    currentRejectionTemplates.unshift({",
  "      id: pb.authStore.model ? pb.authStore.model.id + '_' + Date.now() : 'tpl_' + Date.now(),",
  "      name: 'New Rejection Reason',",
  "      subject: emailTemplateDefaults.rejected.subject,",
  "      body: emailTemplateDefaults.rejected.body",
  "    });",
  "    renderRejectionTemplates();",
  "    markSettingsDirty();",
  "  });",
  "}",
  "",
  "renderLibraryParticipationCheckboxes = async function renderLibraryParticipationCheckboxes() {",
  "  const container = document.getElementById('enabled-libraries-checkbox-container');",
  "  if (!container || container.getAttribute('data-loaded') === 'true') return;",
  "",
  "  if (organizationsStatus === 'loading') {",
  "    container.innerHTML = '<div class=\"p-3 text-muted\">Organizations loading...</div>';",
  "    return;",
  "  }",
  "",
  "  if (organizationsStatus === 'error') {",
  "    container.innerHTML = '<div class=\"p-3 text-warning\">Polaris connected, but organizations could not be loaded. Some setup options may be unavailable until this sync succeeds.</div>';",
  "    return;",
  "  }",
  "",
  "  try {",
  "    const orgs = await pb.collection('polaris_organizations').getFullList({",
  "      filter: 'organizationCodeId = \"2\"',",
  "      sort: 'displayName',",
  "      requestKey: 'polaris-orgs-participation'",
  "    });",
  "",
  "    if (!orgs.length) {",
  "      if (organizationsStatus === 'not_loaded') {",
  "        container.innerHTML = '<div class=\"p-3 text-muted\">Organizations have not been synced yet. Use Settings > Polaris > Sync Polaris Organizations Now.</div>';",
  "      } else {",
  "        container.innerHTML = '<div class=\"p-3 text-muted\">Organization sync completed, but no library organizations were returned.</div>';",
  "      }",
  "      return;",
  "    }",
  "",
  "    setOrganizationsStatus('loaded', `Polaris organizations loaded. ${orgs.length} library organization${orgs.length === 1 ? '' : 's'} available. Leave all libraries unchecked to enable all organizations.`);",
  "    container.innerHTML = `",
  "      <table class=\"table table-sm table-hover mb-0\">",
  "        <thead class=\"bg-white library-table-head\">",
  "          <tr>",
  "            <th class=\"library-enable-col\">Enable</th>",
  "            <th>Library name</th>",
  "            <th class=\"library-id-col\">ID</th>",
  "          </tr>",
  "        </thead>",
  "        <tbody>",
  "          ${orgs.map(org => `",
  "            <tr>",
  "              <td class=\"align-middle\">",
  "                <div class=\"custom-control custom-checkbox\">",
  "                  <input type=\"checkbox\" class=\"custom-control-input lib-participation-cb\" id=\"lib-p-${org.organizationId}\" value=\"${org.organizationId}\">",
  "                  <label class=\"custom-control-label\" for=\"lib-p-${org.organizationId}\"></label>",
  "                </div>",
  "              </td>",
  "              <td class=\"align-middle font-weight-bold\">${escapeAttr(org.displayName || org.name)}</td>",
  "              <td class=\"align-middle text-muted small\">${org.organizationId}</td>",
  "            </tr>",
  "          `).join('')}",
  "        </tbody>",
  "      </table>",
  "    `;",
  "",
  "    container.setAttribute('data-loaded', 'true');",
  "",
  "    // Restore checked state if we have it",
  "    if (lastWorkflowEnabledList) {",
  "      const checkboxes = container.querySelectorAll('.lib-participation-cb');",
  "      checkboxes.forEach(cb => {",
  "        cb.checked = lastWorkflowEnabledList.indexOf(cb.value) >= 0;",
  "      });",
  "    }",
  "  } catch (err) {",
  "    console.error('Failed to load libraries for participation list', err);",
  "    setOrganizationsStatus('error', 'Polaris connected, but organizations could not be loaded. Some setup options may be unavailable until this sync succeeds.');",
  "    container.innerHTML = '<div class=\"p-3 text-warning\">Polaris connected, but organizations could not be loaded. Some setup options may be unavailable until this sync succeeds.</div>';",
  "  }",
  "}",
  "",
  "collectEnabledLibraryIds = function collectEnabledLibraryIds() {",
  "  const container = document.getElementById('enabled-libraries-checkbox-container');",
  "  if (!container) return '';",
  "  const checked = Array.from(container.querySelectorAll('.lib-participation-cb:checked')).map(cb => cb.value);",
  "  return checked.join(',');",
  "}",
  ""
].join('\n');

export function install(env) {
  runLegacyModule(env, source);
}
