export function createModalContext(state) {
  return {
    pb: state.pb,
    formatMap: state.formatMap,
    availableFormats: state.availableFormats,
    publicationOptions: state.publicationOptions,
    get currentRejectionTemplates() { return state.currentRejectionTemplates; },
    get currentSuggestions() { return state.currentSuggestions; },
    get allSuggestions() { return state.allSuggestions; },
    get verifiedBibId() { return state.verifiedBibId; },
    get workflowSettings() { return state.workflowSettings; },
    get currentAdditionalFieldDefinitions() { return state.currentAdditionalFieldDefinitions; },
    get currentFormatRules() { return state.currentFormatRules; },
    setVerifiedBibId: state.setVerifiedBibId,
    get modal() { return document.getElementById('editModal'); },
    get id() { return document.getElementById('edit-id'); },
    get title() { return document.getElementById('edit-title'); },
    get author() { return document.getElementById('edit-author'); },
    get identifier() { return document.getElementById('edit-identifier'); },
    get bibid() { return document.getElementById('edit-bibid'); },
    get format() { return document.getElementById('edit-format'); },
    get publication() { return document.getElementById('edit-publication'); },
    get exactPublicationDate() { return document.getElementById('edit-exact-publication-date'); },
    get autohold() { return document.getElementById('edit-autohold'); },
    get action() { return document.getElementById('edit-action'); },
    get nextStatus() { return document.getElementById('edit-next-status'); },
    get notes() { return document.getElementById('edit-notes'); },
    get rejectionTemplate() { return document.getElementById('edit-rejection-template'); },
    get submitBtn() { return document.getElementById('edit-submit-btn'); },
    get bibInfoDisplay() { return document.getElementById('bib-info-display'); },
    get bibInfoText() { return document.getElementById('bib-info-text'); },
    get selectedPolarisBibId() { return document.getElementById('selectedPolarisBibId'); },
    get selectedPolarisTitle() { return document.getElementById('selectedPolarisTitle'); },
    get selectedPolarisAuthor() { return document.getElementById('selectedPolarisAuthor'); },
    get selectedPolarisIdentifier() { return document.getElementById('selectedPolarisIdentifier'); },
    get selectedPolarisPublication() { return document.getElementById('selectedPolarisPublication'); },
    get selectedPolarisFormat() { return document.getElementById('selectedPolarisFormat'); },
    get emailPurchaseReminder() { return document.getElementById('edit-email-purchase-reminder'); },
    get bibidHint() { return document.getElementById('edit-bibid-hint'); },
    get bibidRequiredMarker() { return document.getElementById('edit-bibid-required'); },
    get auditPreview() { return document.getElementById('edit-pending-audit-preview'); },
    get auditPreviewText() { return document.getElementById('edit-pending-audit-preview-text'); },
    get rejectionContainer() { return document.getElementById('edit-rejection-template-container'); },
    get rejectionAvailability() { return document.getElementById('edit-rejection-template-availability'); },
    get leapBibLinkContainer() { return document.getElementById('edit-leap-bib-link-container'); },
    get externalSearchContainer() { return document.getElementById('edit-external-search-container'); },
    get purchaseReminderContainer() { return document.getElementById('edit-purchase-reminder-container'); },
    get purchaseReminderHelp() { return document.getElementById('edit-purchase-reminder-help'); },
    get purchaseReminderCheckbox() { return document.getElementById('edit-email-purchase-reminder'); },
    get patronContextBlock() { return document.getElementById('edit-patron-context'); },
    get workflowTags() { return document.getElementById('edit-workflow-tags'); },
    get claimState() { return document.getElementById('edit-claim-state'); },
    get metadataBlock() { return document.getElementById('edit-metadata'); },
    get modalLabel() { return document.getElementById('editModalLabel'); },
    holdingsLookupUnavailable: false
  };
}
