[CmdletBinding()]
param(
    [string]$Workspace = (Join-Path $HOME 'ASAP-Review'),
    [string]$RepositoryUrl = 'https://github.com/clcdpc/asap-pocketbase.git',
    [string]$ToolingRef = 'codex/csharp-port'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$BootstrapVersion = '0.1.7'

function Invoke-Native {
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [Parameter(Mandatory)][string[]]$ArgumentList
    )

    & $FilePath @ArgumentList
    if ($LASTEXITCODE -ne 0) {
        throw "$FilePath exited with code $LASTEXITCODE."
    }
}

function Write-Wrapper {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$ToolingVersion
    )

    $content = @"
# Generated by ASAP Docker Review tooling $ToolingVersion.
`$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

`$repoRoot = Join-Path `$PSScriptRoot 'asap-pocketbase'
`$launcher = Join-Path `$repoRoot 'scripts/review/Invoke-AsapReview.ps1'
`$config = Join-Path `$PSScriptRoot 'review.local.json'

if (-not (Test-Path -LiteralPath `$launcher)) {
    throw "ASAP review launcher was not found: `$launcher. Run Bootstrap-AsapReview.ps1 again."
}
if (-not (Test-Path -LiteralPath `$config)) {
    throw "ASAP review configuration was not found: `$config. Run Bootstrap-AsapReview.ps1 again."
}

& pwsh -NoProfile -File `$launcher -Config `$config @args
exit `$LASTEXITCODE
"@

    Set-Content -LiteralPath $Path -Value $content -Encoding utf8NoBOM
}

Write-Host "ASAP review bootstrap $BootstrapVersion"

if ($PSVersionTable.PSVersion.Major -lt 7) {
    throw "PowerShell 7 or later is required. Current version: $($PSVersionTable.PSVersion)."
}
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    throw 'Git was not found. Install Git for Windows and rerun bootstrap.'
}

$Workspace = [System.IO.Path]::GetFullPath($Workspace)
$repoRoot = Join-Path $Workspace 'asap-pocketbase'
$configPath = Join-Path $Workspace 'review.local.json'
$wrapperPath = Join-Path $Workspace 'Review-Asap.ps1'

New-Item -ItemType Directory -Path $Workspace -Force | Out-Null

if (-not (Test-Path -LiteralPath $repoRoot)) {
    Write-Host "Cloning ASAP into $repoRoot..."
    Invoke-Native git @('clone', $RepositoryUrl, $repoRoot)
}
elseif (-not (Test-Path -LiteralPath (Join-Path $repoRoot '.git'))) {
    throw "The repository path already exists but is not a Git clone: $repoRoot"
}

$dirty = (@(& git -C $repoRoot status --porcelain) -join "`n").Trim()
if ($LASTEXITCODE -ne 0) {
    throw "Could not inspect the ASAP review clone: $repoRoot"
}
if ($dirty) {
    throw "The ASAP review clone has local changes. Resolve them before running bootstrap: $repoRoot"
}

# Bootstrap always synchronizes the dedicated tooling checkout.
Write-Host "Synchronizing ASAP review tooling from $ToolingRef..."
Invoke-Native git @('-C', $repoRoot, 'fetch', 'origin', $ToolingRef)
Invoke-Native git @('-C', $repoRoot, 'checkout', '--force', '-B', 'asap-review-tooling', 'FETCH_HEAD')
Invoke-Native git @('-C', $repoRoot, 'worktree', 'prune')

$gitBootstrapPath = Join-Path $repoRoot 'scripts/review/Bootstrap-AsapReview.ps1'
$launcherPath = Join-Path $repoRoot 'scripts/review/Invoke-AsapReview.ps1'
$prerequisitePath = Join-Path $repoRoot 'scripts/review/Test-AsapReviewPrerequisites.ps1'
$tlsInitializerPath = Join-Path $repoRoot 'scripts/review/Initialize-AsapReviewTls.ps1'
$configTemplatePath = Join-Path $repoRoot 'dev/review/review.example.json'
$versionPath = Join-Path $repoRoot 'dev/review/VERSION'

foreach ($requiredPath in @($gitBootstrapPath, $launcherPath, $prerequisitePath, $tlsInitializerPath, $configTemplatePath, $versionPath)) {
    if (-not (Test-Path -LiteralPath $requiredPath)) {
        throw "The selected tooling ref '$ToolingRef' does not contain required review tooling: $requiredPath"
    }
}

$toolingVersion = (Get-Content -LiteralPath $versionPath -Raw).Trim()
if (-not $toolingVersion) {
    throw "The review tooling version file is empty: $versionPath"
}

Write-Host "Checking review prerequisites for tooling $toolingVersion..."
& pwsh -NoProfile -File $prerequisitePath
if ($LASTEXITCODE -ne 0) {
    throw 'ASAP review prerequisites are not satisfied. Correct the reported prerequisite and rerun bootstrap.'
}

Write-Host 'Preparing the trusted localhost HTTPS certificate...'
& pwsh -NoProfile -File $tlsInitializerPath -Workspace $Workspace -ReviewStatePath (Join-Path $repoRoot '.review/current.json')
if ($LASTEXITCODE -ne 0) {
    throw 'ASAP review localhost HTTPS certificate setup failed.'
}

if (-not (Test-Path -LiteralPath $configPath)) {
    Copy-Item -LiteralPath $configTemplatePath -Destination $configPath
    Write-Host "Created review configuration: $configPath"
}
else {
    Write-Host "Keeping existing review configuration: $configPath"
}

Write-Wrapper -Path $wrapperPath -ToolingVersion $toolingVersion

Write-Host ''
Write-Host "ASAP review bootstrap complete. Tooling version: $toolingVersion"
Write-Host ''
Write-Host 'Next:'
Write-Host "1. Edit: $configPath"
Write-Host '2. Run a commit:'
Write-Host "   pwsh `"$wrapperPath`" -Commit <commit-sha>"
Write-Host ''
Write-Host 'To refresh the review tooling later, rerun the canonical bootstrap:'
Write-Host "   pwsh `"$gitBootstrapPath`" -RepositoryUrl `"$RepositoryUrl`" -ToolingRef `"$ToolingRef`""
